class ::Passkey < ::ApplicationRecord
    extend ::ActiveRecord::Base::ClassMethods[::Passkey, ::Passkey::ActiveRecord_Relation, ::Integer]

    module ::Passkey::GeneratedAttributeMethods
        def id: -> ::Integer

        def id=: (::Integer) -> ::Integer

        def id?: -> bool

        def id_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

        def id_change: -> [::Integer?, ::Integer?]

        def id_will_change!: -> void

        def id_was: -> ::Integer?

        def id_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

        def id_previous_change: -> ::Array[::Integer?]?

        def id_previously_was: -> ::Integer?

        def id_before_last_save: -> ::Integer?

        def id_change_to_be_saved: -> ::Array[::Integer?]?

        def id_in_database: -> ::Integer?

        def saved_change_to_id: -> ::Array[::Integer?]?

        def saved_change_to_id?: -> bool

        def will_save_change_to_id?: -> bool

        def restore_id!: -> void

        def clear_id_change: -> void

        def id_before_type_cast: -> ::Integer

        def id_for_database: -> ::Integer

        def created_at: -> ::ActiveSupport::TimeWithZone

        def created_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

        def created_at?: -> bool

        def created_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

        def created_at_change: -> [::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone?]

        def created_at_will_change!: -> void

        def created_at_was: -> ::ActiveSupport::TimeWithZone?

        def created_at_previously_changed?: (
            ?from: ::ActiveSupport::TimeWithZone?,
            ?to: ::ActiveSupport::TimeWithZone?
        ) -> bool

        def created_at_previous_change: -> ::Array[::ActiveSupport::TimeWithZone?]?

        def created_at_previously_was: -> ::ActiveSupport::TimeWithZone?

        def created_at_before_last_save: -> ::ActiveSupport::TimeWithZone?

        def created_at_change_to_be_saved: -> ::Array[::ActiveSupport::TimeWithZone?]?

        def created_at_in_database: -> ::ActiveSupport::TimeWithZone?

        def saved_change_to_created_at: -> ::Array[::ActiveSupport::TimeWithZone?]?

        def saved_change_to_created_at?: -> bool

        def will_save_change_to_created_at?: -> bool

        def restore_created_at!: -> void

        def clear_created_at_change: -> void

        def created_at_before_type_cast: -> ::Time

        def created_at_for_database: -> ::Time

        def external_id: -> ::String?

        def external_id=: (::String?) -> ::String?

        def external_id?: -> bool

        def external_id_changed?: (?from: ::String?, ?to: ::String?) -> bool

        def external_id_change: -> [::String?, ::String?]

        def external_id_will_change!: -> void

        def external_id_was: -> ::String?

        def external_id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

        def external_id_previous_change: -> ::Array[::String?]?

        def external_id_previously_was: -> ::String?

        def external_id_before_last_save: -> ::String?

        def external_id_change_to_be_saved: -> ::Array[::String?]?

        def external_id_in_database: -> ::String?

        def saved_change_to_external_id: -> ::Array[::String?]?

        def saved_change_to_external_id?: -> bool

        def will_save_change_to_external_id?: -> bool

        def restore_external_id!: -> void

        def clear_external_id_change: -> void

        def external_id_before_type_cast: -> ::String?

        def external_id_for_database: -> ::String?

        def label: -> ::String

        def label=: (::String) -> ::String

        def label?: -> bool

        def label_changed?: (?from: ::String?, ?to: ::String?) -> bool

        def label_change: -> [::String?, ::String?]

        def label_will_change!: -> void

        def label_was: -> ::String?

        def label_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

        def label_previous_change: -> ::Array[::String?]?

        def label_previously_was: -> ::String?

        def label_before_last_save: -> ::String?

        def label_change_to_be_saved: -> ::Array[::String?]?

        def label_in_database: -> ::String?

        def saved_change_to_label: -> ::Array[::String?]?

        def saved_change_to_label?: -> bool

        def will_save_change_to_label?: -> bool

        def restore_label!: -> void

        def clear_label_change: -> void

        def label_before_type_cast: -> ::String

        def label_for_database: -> ::String

        def last_used_at: -> ::ActiveSupport::TimeWithZone?

        def last_used_at=: (::ActiveSupport::TimeWithZone?) -> ::ActiveSupport::TimeWithZone?

        def last_used_at?: -> bool

        def last_used_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

        def last_used_at_change: -> [::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone?]

        def last_used_at_will_change!: -> void

        def last_used_at_was: -> ::ActiveSupport::TimeWithZone?

        def last_used_at_previously_changed?: (
            ?from: ::ActiveSupport::TimeWithZone?,
            ?to: ::ActiveSupport::TimeWithZone?
        ) -> bool

        def last_used_at_previous_change: -> ::Array[::ActiveSupport::TimeWithZone?]?

        def last_used_at_previously_was: -> ::ActiveSupport::TimeWithZone?

        def last_used_at_before_last_save: -> ::ActiveSupport::TimeWithZone?

        def last_used_at_change_to_be_saved: -> ::Array[::ActiveSupport::TimeWithZone?]?

        def last_used_at_in_database: -> ::ActiveSupport::TimeWithZone?

        def saved_change_to_last_used_at: -> ::Array[::ActiveSupport::TimeWithZone?]?

        def saved_change_to_last_used_at?: -> bool

        def will_save_change_to_last_used_at?: -> bool

        def restore_last_used_at!: -> void

        def clear_last_used_at_change: -> void

        def last_used_at_before_type_cast: -> ::Time?

        def last_used_at_for_database: -> ::Time?

        def public_key: -> ::String?

        def public_key=: (::String?) -> ::String?

        def public_key?: -> bool

        def public_key_changed?: (?from: ::String?, ?to: ::String?) -> bool

        def public_key_change: -> [::String?, ::String?]

        def public_key_will_change!: -> void

        def public_key_was: -> ::String?

        def public_key_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

        def public_key_previous_change: -> ::Array[::String?]?

        def public_key_previously_was: -> ::String?

        def public_key_before_last_save: -> ::String?

        def public_key_change_to_be_saved: -> ::Array[::String?]?

        def public_key_in_database: -> ::String?

        def saved_change_to_public_key: -> ::Array[::String?]?

        def saved_change_to_public_key?: -> bool

        def will_save_change_to_public_key?: -> bool

        def restore_public_key!: -> void

        def clear_public_key_change: -> void

        def public_key_before_type_cast: -> ::String?

        def public_key_for_database: -> ::String?

        def sign_count: -> ::Integer?

        def sign_count=: (::Integer?) -> ::Integer?

        def sign_count?: -> bool

        def sign_count_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

        def sign_count_change: -> [::Integer?, ::Integer?]

        def sign_count_will_change!: -> void

        def sign_count_was: -> ::Integer?

        def sign_count_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

        def sign_count_previous_change: -> ::Array[::Integer?]?

        def sign_count_previously_was: -> ::Integer?

        def sign_count_before_last_save: -> ::Integer?

        def sign_count_change_to_be_saved: -> ::Array[::Integer?]?

        def sign_count_in_database: -> ::Integer?

        def saved_change_to_sign_count: -> ::Array[::Integer?]?

        def saved_change_to_sign_count?: -> bool

        def will_save_change_to_sign_count?: -> bool

        def restore_sign_count!: -> void

        def clear_sign_count_change: -> void

        def sign_count_before_type_cast: -> ::Integer?

        def sign_count_for_database: -> ::Integer?

        def updated_at: -> ::ActiveSupport::TimeWithZone

        def updated_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

        def updated_at?: -> bool

        def updated_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

        def updated_at_change: -> [::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone?]

        def updated_at_will_change!: -> void

        def updated_at_was: -> ::ActiveSupport::TimeWithZone?

        def updated_at_previously_changed?: (
            ?from: ::ActiveSupport::TimeWithZone?,
            ?to: ::ActiveSupport::TimeWithZone?
        ) -> bool

        def updated_at_previous_change: -> ::Array[::ActiveSupport::TimeWithZone?]?

        def updated_at_previously_was: -> ::ActiveSupport::TimeWithZone?

        def updated_at_before_last_save: -> ::ActiveSupport::TimeWithZone?

        def updated_at_change_to_be_saved: -> ::Array[::ActiveSupport::TimeWithZone?]?

        def updated_at_in_database: -> ::ActiveSupport::TimeWithZone?

        def saved_change_to_updated_at: -> ::Array[::ActiveSupport::TimeWithZone?]?

        def saved_change_to_updated_at?: -> bool

        def will_save_change_to_updated_at?: -> bool

        def restore_updated_at!: -> void

        def clear_updated_at_change: -> void

        def updated_at_before_type_cast: -> ::Time

        def updated_at_for_database: -> ::Time

        def user_id: -> ::Integer

        def user_id=: (::Integer) -> ::Integer

        def user_id?: -> bool

        def user_id_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

        def user_id_change: -> [::Integer?, ::Integer?]

        def user_id_will_change!: -> void

        def user_id_was: -> ::Integer?

        def user_id_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

        def user_id_previous_change: -> ::Array[::Integer?]?

        def user_id_previously_was: -> ::Integer?

        def user_id_before_last_save: -> ::Integer?

        def user_id_change_to_be_saved: -> ::Array[::Integer?]?

        def user_id_in_database: -> ::Integer?

        def saved_change_to_user_id: -> ::Array[::Integer?]?

        def saved_change_to_user_id?: -> bool

        def will_save_change_to_user_id?: -> bool

        def restore_user_id!: -> void

        def clear_user_id_change: -> void

        def user_id_before_type_cast: -> ::Integer

        def user_id_for_database: -> ::Integer
    end
    include ::Passkey::GeneratedAttributeMethods
    module ::Passkey::GeneratedAliasAttributeMethods
        include ::Passkey::GeneratedAttributeMethods

        alias id_value id

        alias id_value= id=

        alias id_value? id?

        alias id_value_changed? id_changed?

        alias id_value_change id_change

        alias id_value_will_change! id_will_change!

        alias id_value_was id_was

        alias id_value_previously_changed? id_previously_changed?

        alias id_value_previous_change id_previous_change

        alias id_value_previously_was id_previously_was

        alias id_value_before_last_save id_before_last_save

        alias id_value_change_to_be_saved id_change_to_be_saved

        alias id_value_in_database id_in_database

        alias saved_change_to_id_value saved_change_to_id

        alias saved_change_to_id_value? saved_change_to_id?

        alias will_save_change_to_id_value? will_save_change_to_id?

        alias restore_id_value! restore_id!

        alias clear_id_value_change clear_id_change

        alias id_value_before_type_cast id_before_type_cast

        alias id_value_for_database id_for_database
    end
    include ::Passkey::GeneratedAliasAttributeMethods

    def user: -> ::User
    def user=: (::User?) -> ::User?
    def reload_user: -> ::User?
    def build_user: (untyped) -> ::User
    def create_user: (untyped) -> ::User
    def create_user!: (untyped) -> ::User
    module ::Passkey::GeneratedAssociationMethods
    end
    include ::Passkey::GeneratedAssociationMethods

    module ::Passkey::GeneratedRelationMethods
    end

    class ::Passkey::ActiveRecord_Relation < ::ActiveRecord::Relation
        include ::Enumerable[::Passkey]
        include ::Passkey::GeneratedRelationMethods
        include ::ActiveRecord::Relation::Methods[::Passkey, ::Integer]
    end

    class ::Passkey::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
        include ::Enumerable[::Passkey]
        include ::Passkey::GeneratedRelationMethods
        include ::ActiveRecord::Relation::Methods[::Passkey, ::Integer]

        def build:
            (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ -> untyped } -> ::Passkey
            | (
                ::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes
            ) ?{
                -> untyped
            } -> ::Array[::Passkey]
        def create:
            (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ -> untyped } -> ::Passkey
            | (
                ::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes
            ) ?{
                -> untyped
            } -> ::Array[::Passkey]
        def create!:
            (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ -> untyped } -> ::Passkey
            | (
                ::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes
            ) ?{
                -> untyped
            } -> ::Array[::Passkey]
        def reload: -> ::Array[::Passkey]

        def replace: (::Array[::Passkey]) -> void
        def delete: (*::Passkey | ::Integer) -> ::Array[::Passkey]
        def destroy: (*::Passkey | ::Integer) -> ::Array[::Passkey]
        def <<: (*::Passkey | ::Array[::Passkey]) -> self
        def `prepend`: (*::Passkey | ::Array[::Passkey]) -> self
    end
end

class ::ApplicationRecord < ::ActiveRecord::Base
end

class ::User < ::ApplicationRecord
end
