class ::UserBillReminder < ::ApplicationRecord
    extend ::ActiveRecord::Base::ClassMethods[::UserBillReminder, ::UserBillReminder::ActiveRecord_Relation, ::Integer]

    module ::UserBillReminder::GeneratedAttributeMethods
        def id: -> ::Integer

        def id=: (::Integer) -> ::Integer

        def id?: -> bool

        def id_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

        def id_change: -> [::Integer?, ::Integer?]

        def id_will_change!: -> void

        def id_was: -> ::Integer?

        def id_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

        def id_previous_change: -> ::Array[::Integer?]?

        def id_previously_was: -> ::Integer?

        def id_before_last_save: -> ::Integer?

        def id_change_to_be_saved: -> ::Array[::Integer?]?

        def id_in_database: -> ::Integer?

        def saved_change_to_id: -> ::Array[::Integer?]?

        def saved_change_to_id?: -> bool

        def will_save_change_to_id?: -> bool

        def restore_id!: -> void

        def clear_id_change: -> void

        def id_before_type_cast: -> ::Integer

        def id_for_database: -> ::Integer

        def user_id: -> ::Integer

        def user_id=: (::Integer) -> ::Integer

        def user_id?: -> bool

        def user_id_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

        def user_id_change: -> [::Integer?, ::Integer?]

        def user_id_will_change!: -> void

        def user_id_was: -> ::Integer?

        def user_id_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

        def user_id_previous_change: -> ::Array[::Integer?]?

        def user_id_previously_was: -> ::Integer?

        def user_id_before_last_save: -> ::Integer?

        def user_id_change_to_be_saved: -> ::Array[::Integer?]?

        def user_id_in_database: -> ::Integer?

        def saved_change_to_user_id: -> ::Array[::Integer?]?

        def saved_change_to_user_id?: -> bool

        def will_save_change_to_user_id?: -> bool

        def restore_user_id!: -> void

        def clear_user_id_change: -> void

        def user_id_before_type_cast: -> ::Integer

        def user_id_for_database: -> ::Integer

        def bill_id: -> ::Integer

        def bill_id=: (::Integer) -> ::Integer

        def bill_id?: -> bool

        def bill_id_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

        def bill_id_change: -> [::Integer?, ::Integer?]

        def bill_id_will_change!: -> void

        def bill_id_was: -> ::Integer?

        def bill_id_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

        def bill_id_previous_change: -> ::Array[::Integer?]?

        def bill_id_previously_was: -> ::Integer?

        def bill_id_before_last_save: -> ::Integer?

        def bill_id_change_to_be_saved: -> ::Array[::Integer?]?

        def bill_id_in_database: -> ::Integer?

        def saved_change_to_bill_id: -> ::Array[::Integer?]?

        def saved_change_to_bill_id?: -> bool

        def will_save_change_to_bill_id?: -> bool

        def restore_bill_id!: -> void

        def clear_bill_id_change: -> void

        def bill_id_before_type_cast: -> ::Integer

        def bill_id_for_database: -> ::Integer

        def sent_at: -> ::ActiveSupport::TimeWithZone?

        def sent_at=: (::ActiveSupport::TimeWithZone?) -> ::ActiveSupport::TimeWithZone?

        def sent_at?: -> bool

        def sent_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

        def sent_at_change: -> [::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone?]

        def sent_at_will_change!: -> void

        def sent_at_was: -> ::ActiveSupport::TimeWithZone?

        def sent_at_previously_changed?: (
            ?from: ::ActiveSupport::TimeWithZone?,
            ?to: ::ActiveSupport::TimeWithZone?
        ) -> bool

        def sent_at_previous_change: -> ::Array[::ActiveSupport::TimeWithZone?]?

        def sent_at_previously_was: -> ::ActiveSupport::TimeWithZone?

        def sent_at_before_last_save: -> ::ActiveSupport::TimeWithZone?

        def sent_at_change_to_be_saved: -> ::Array[::ActiveSupport::TimeWithZone?]?

        def sent_at_in_database: -> ::ActiveSupport::TimeWithZone?

        def saved_change_to_sent_at: -> ::Array[::ActiveSupport::TimeWithZone?]?

        def saved_change_to_sent_at?: -> bool

        def will_save_change_to_sent_at?: -> bool

        def restore_sent_at!: -> void

        def clear_sent_at_change: -> void

        def sent_at_before_type_cast: -> ::Time?

        def sent_at_for_database: -> ::Time?

        def created_at: -> ::ActiveSupport::TimeWithZone

        def created_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

        def created_at?: -> bool

        def created_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

        def created_at_change: -> [::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone?]

        def created_at_will_change!: -> void

        def created_at_was: -> ::ActiveSupport::TimeWithZone?

        def created_at_previously_changed?: (
            ?from: ::ActiveSupport::TimeWithZone?,
            ?to: ::ActiveSupport::TimeWithZone?
        ) -> bool

        def created_at_previous_change: -> ::Array[::ActiveSupport::TimeWithZone?]?

        def created_at_previously_was: -> ::ActiveSupport::TimeWithZone?

        def created_at_before_last_save: -> ::ActiveSupport::TimeWithZone?

        def created_at_change_to_be_saved: -> ::Array[::ActiveSupport::TimeWithZone?]?

        def created_at_in_database: -> ::ActiveSupport::TimeWithZone?

        def saved_change_to_created_at: -> ::Array[::ActiveSupport::TimeWithZone?]?

        def saved_change_to_created_at?: -> bool

        def will_save_change_to_created_at?: -> bool

        def restore_created_at!: -> void

        def clear_created_at_change: -> void

        def created_at_before_type_cast: -> ::Time

        def created_at_for_database: -> ::Time

        def updated_at: -> ::ActiveSupport::TimeWithZone

        def updated_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

        def updated_at?: -> bool

        def updated_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

        def updated_at_change: -> [::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone?]

        def updated_at_will_change!: -> void

        def updated_at_was: -> ::ActiveSupport::TimeWithZone?

        def updated_at_previously_changed?: (
            ?from: ::ActiveSupport::TimeWithZone?,
            ?to: ::ActiveSupport::TimeWithZone?
        ) -> bool

        def updated_at_previous_change: -> ::Array[::ActiveSupport::TimeWithZone?]?

        def updated_at_previously_was: -> ::ActiveSupport::TimeWithZone?

        def updated_at_before_last_save: -> ::ActiveSupport::TimeWithZone?

        def updated_at_change_to_be_saved: -> ::Array[::ActiveSupport::TimeWithZone?]?

        def updated_at_in_database: -> ::ActiveSupport::TimeWithZone?

        def saved_change_to_updated_at: -> ::Array[::ActiveSupport::TimeWithZone?]?

        def saved_change_to_updated_at?: -> bool

        def will_save_change_to_updated_at?: -> bool

        def restore_updated_at!: -> void

        def clear_updated_at_change: -> void

        def updated_at_before_type_cast: -> ::Time

        def updated_at_for_database: -> ::Time
    end
    include ::UserBillReminder::GeneratedAttributeMethods
    module ::UserBillReminder::GeneratedAliasAttributeMethods
        include ::UserBillReminder::GeneratedAttributeMethods

        alias id_value id

        alias id_value= id=

        alias id_value? id?

        alias id_value_changed? id_changed?

        alias id_value_change id_change

        alias id_value_will_change! id_will_change!

        alias id_value_was id_was

        alias id_value_previously_changed? id_previously_changed?

        alias id_value_previous_change id_previous_change

        alias id_value_previously_was id_previously_was

        alias id_value_before_last_save id_before_last_save

        alias id_value_change_to_be_saved id_change_to_be_saved

        alias id_value_in_database id_in_database

        alias saved_change_to_id_value saved_change_to_id

        alias saved_change_to_id_value? saved_change_to_id?

        alias will_save_change_to_id_value? will_save_change_to_id?

        alias restore_id_value! restore_id!

        alias clear_id_value_change clear_id_change

        alias id_value_before_type_cast id_before_type_cast

        alias id_value_for_database id_for_database
    end
    include ::UserBillReminder::GeneratedAliasAttributeMethods

    def user: -> ::User
    def user=: (::User?) -> ::User?
    def reload_user: -> ::User?
    def build_user: (untyped) -> ::User
    def create_user: (untyped) -> ::User
    def create_user!: (untyped) -> ::User
    def bill: -> ::Bill
    def bill=: (::Bill?) -> ::Bill?
    def reload_bill: -> ::Bill?
    def build_bill: (untyped) -> ::Bill
    def create_bill: (untyped) -> ::Bill
    def create_bill!: (untyped) -> ::Bill
    module ::UserBillReminder::GeneratedAssociationMethods
    end
    include ::UserBillReminder::GeneratedAssociationMethods

    module ::UserBillReminder::GeneratedRelationMethods
    end

    class ::UserBillReminder::ActiveRecord_Relation < ::ActiveRecord::Relation
        include ::Enumerable[::UserBillReminder]
        include ::UserBillReminder::GeneratedRelationMethods
        include ::ActiveRecord::Relation::Methods[::UserBillReminder, ::Integer]
    end

    class ::UserBillReminder::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
        include ::Enumerable[::UserBillReminder]
        include ::UserBillReminder::GeneratedRelationMethods
        include ::ActiveRecord::Relation::Methods[::UserBillReminder, ::Integer]

        def build:
            (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ -> untyped } -> ::UserBillReminder
            | (
                ::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes
            ) ?{
                -> untyped
            } -> ::Array[::UserBillReminder]
        def create:
            (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ -> untyped } -> ::UserBillReminder
            | (
                ::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes
            ) ?{
                -> untyped
            } -> ::Array[::UserBillReminder]
        def create!:
            (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ -> untyped } -> ::UserBillReminder
            | (
                ::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes
            ) ?{
                -> untyped
            } -> ::Array[::UserBillReminder]
        def reload: -> ::Array[::UserBillReminder]

        def replace: (::Array[::UserBillReminder]) -> void
        def delete: (*::UserBillReminder | ::Integer) -> ::Array[::UserBillReminder]
        def destroy: (*::UserBillReminder | ::Integer) -> ::Array[::UserBillReminder]
        def <<: (*::UserBillReminder | ::Array[::UserBillReminder]) -> self
        def `prepend`: (*::UserBillReminder | ::Array[::UserBillReminder]) -> self
    end
end

class ::ApplicationRecord < ::ActiveRecord::Base
end

class ::User < ::ApplicationRecord
end

class ::Bill < ::ApplicationRecord
end
