# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `digest-crc` gem.
# Please instead update this file by running `bin/tapioca gem digest-crc`.


# Base class for all CRC algorithms.
#
# source://digest-crc//lib/digest/crc.rb#7
class Digest::CRC < ::Digest::Class
  # Initializes the CRC checksum.
  #
  # @return [CRC] a new instance of CRC
  #
  # source://digest-crc//lib/digest/crc.rb#85
  def initialize; end

  # @see #update
  #
  # source://digest-crc//lib/digest/crc.rb#176
  def <<(data); end

  # The input block length.
  #
  # @return [1]
  #
  # source://digest-crc//lib/digest/crc.rb#100
  def block_length; end

  # The resulting CRC checksum.
  #
  # @return [Integer] The resulting CRC checksum.
  #
  # source://digest-crc//lib/digest/crc.rb#197
  def checksum; end

  # The length of the digest.
  #
  # @return [Integer] The length in bytes.
  #
  # source://digest-crc//lib/digest/crc.rb#110
  def digest_length; end

  # Finishes the CRC checksum calculation.
  #
  # @see pack
  #
  # source://digest-crc//lib/digest/crc.rb#206
  def finish; end

  # Resets the CRC checksum.
  #
  # @return [Integer] The default value of the CRC checksum.
  #
  # source://digest-crc//lib/digest/crc.rb#187
  def reset; end

  # Updates the CRC checksum with the given data.
  #
  # @param data [String] The data to update the CRC checksum with.
  # @raise [NotImplementedError] If WIDTH, TABLE, or REFLECT_INPUT constants are not set properly.
  #
  # source://digest-crc//lib/digest/crc.rb#123
  def update(data); end

  class << self
    # Calculates the CRC checksum.
    #
    # @param data [String] The given data.
    # @return [Integer] The CRC checksum.
    #
    # source://digest-crc//lib/digest/crc.rb#35
    def checksum(data); end

    # Determines whether the library is using the optimized C extensions
    # implementation, or the pure-Ruby implementation.
    #
    # @return [:c_ext, :pure]
    # @since 0.7.0
    #
    # source://digest-crc//lib/digest/crc.rb#74
    def implementation; end

    # Packs the given CRC checksum.
    #
    # @param crc [Integer] The raw CRC checksum.
    # @return [String] The packed CRC checksum.
    #
    # source://digest-crc//lib/digest/crc.rb#51
    def pack(crc); end
  end
end

# Implements the CRC1 algorithm.
#
# source://digest-crc//lib/digest/crc1.rb#7
class Digest::CRC1 < ::Digest::CRC
  # Updates the CRC1 checksum.
  #
  # @param data [String] The data to update the checksum with.
  #
  # source://digest-crc//lib/digest/crc1.rb#27
  def update(data); end

  class << self
    # Packs the CRC1 checksum.
    #
    # @return [String] The CRC1 checksum.
    #
    # source://digest-crc//lib/digest/crc1.rb#17
    def pack(crc); end
  end
end

# Implements the CRC15 algorithm.
#
# @since 0.5.0
#
# source://digest-crc//lib/digest/crc15.rb#9
class Digest::CRC15 < ::Digest::CRC
  def update(_arg0); end
end

# @since 0.5.0
#
# source://digest-crc//lib/digest/crc15.rb#13
Digest::CRC15::REFLECT_INPUT = T.let(T.unsafe(nil), FalseClass)

# Generated by `./pycrc.py --algorithm=table-driven --model=crc-16 --generate=c`
#
# @since 0.5.0
#
# source://digest-crc//lib/digest/crc15.rb#16
Digest::CRC15::TABLE = T.let(T.unsafe(nil), Array)

# @since 0.5.0
#
# source://digest-crc//lib/digest/crc15.rb#11
Digest::CRC15::WIDTH = T.let(T.unsafe(nil), Integer)

# Implements the CRC16 algorithm.
#
# source://digest-crc//lib/digest/crc16.rb#7
class Digest::CRC16 < ::Digest::CRC
  def update(_arg0); end
end

# source://digest-crc//lib/digest/crc16.rb#13
Digest::CRC16::INIT_CRC = T.let(T.unsafe(nil), Integer)

# source://digest-crc//lib/digest/crc16.rb#11
Digest::CRC16::REFLECT_INPUT = T.let(T.unsafe(nil), TrueClass)

# Generated by `./pycrc.py --algorithm=table-driven --model=crc-16`
#
# source://digest-crc//lib/digest/crc16.rb#16
Digest::CRC16::TABLE = T.let(T.unsafe(nil), Array)

# source://digest-crc//lib/digest/crc16.rb#9
Digest::CRC16::WIDTH = T.let(T.unsafe(nil), Integer)

# source://digest-crc//lib/digest/crc1.rb#9
Digest::CRC1::WIDTH = T.let(T.unsafe(nil), Integer)

# Implements the CRC24 algorithm.
#
# source://digest-crc//lib/digest/crc24.rb#7
class Digest::CRC24 < ::Digest::CRC
  def update(_arg0); end
end

# source://digest-crc//lib/digest/crc24.rb#13
Digest::CRC24::INIT_CRC = T.let(T.unsafe(nil), Integer)

# source://digest-crc//lib/digest/crc24.rb#11
Digest::CRC24::REFLECT_INPUT = T.let(T.unsafe(nil), FalseClass)

# Generated by `./pycrc.py --algorithm=table-drive --model=crc24 --generate=c`
#
# source://digest-crc//lib/digest/crc24.rb#16
Digest::CRC24::TABLE = T.let(T.unsafe(nil), Array)

# source://digest-crc//lib/digest/crc24.rb#9
Digest::CRC24::WIDTH = T.let(T.unsafe(nil), Integer)

# Implements the CRC32 algorithm.
#
# source://digest-crc//lib/digest/crc32.rb#7
class Digest::CRC32 < ::Digest::CRC
  def update(_arg0); end
end

# source://digest-crc//lib/digest/crc32.rb#13
Digest::CRC32::INIT_CRC = T.let(T.unsafe(nil), Integer)

# source://digest-crc//lib/digest/crc32.rb#11
Digest::CRC32::REFLECT_INPUT = T.let(T.unsafe(nil), TrueClass)

# Generated by `./pycrc.py --algorithm=table-driven --model=crc-32 --generate=c`
#
# source://digest-crc//lib/digest/crc32.rb#18
Digest::CRC32::TABLE = T.let(T.unsafe(nil), Array)

# source://digest-crc//lib/digest/crc32.rb#9
Digest::CRC32::WIDTH = T.let(T.unsafe(nil), Integer)

# source://digest-crc//lib/digest/crc32.rb#15
Digest::CRC32::XOR_MASK = T.let(T.unsafe(nil), Integer)

# Implements the CRC32c algorithm.
#
# source://digest-crc//lib/digest/crc32c.rb#7
class Digest::CRC32c < ::Digest::CRC32
  def update(_arg0); end
end

# Generated by `./pycrc.py --algorithm=table-driven --model=crc-32c --generate=c`
#
# source://digest-crc//lib/digest/crc32c.rb#10
Digest::CRC32c::TABLE = T.let(T.unsafe(nil), Array)

# Implements the CRC5 algorithm.
#
# source://digest-crc//lib/digest/crc5.rb#7
class Digest::CRC5 < ::Digest::CRC
  # Initializes the CRC5 instance.
  #
  # @return [CRC5] a new instance of CRC5
  #
  # source://digest-crc//lib/digest/crc5.rb#42
  def initialize; end

  def update(_arg0); end
end

# source://digest-crc//lib/digest/crc5.rb#17
Digest::CRC5::CRC_MASK = T.let(T.unsafe(nil), Integer)

# source://digest-crc//lib/digest/crc5.rb#13
Digest::CRC5::INIT_CRC = T.let(T.unsafe(nil), Integer)

# source://digest-crc//lib/digest/crc5.rb#11
Digest::CRC5::REFLECT_INPUT = T.let(T.unsafe(nil), TrueClass)

# Generated by `./pycrc.py --algorithm=table-driven --model=crc-5 --generate=c`
#
# source://digest-crc//lib/digest/crc5.rb#20
Digest::CRC5::TABLE = T.let(T.unsafe(nil), Array)

# source://digest-crc//lib/digest/crc5.rb#9
Digest::CRC5::WIDTH = T.let(T.unsafe(nil), Integer)

# source://digest-crc//lib/digest/crc5.rb#15
Digest::CRC5::XOR_MASK = T.let(T.unsafe(nil), Integer)

# Implements the CRC64 algorithm.
#
# source://digest-crc//lib/digest/crc64.rb#7
class Digest::CRC64 < ::Digest::CRC
  def update(_arg0); end
end

# source://digest-crc//lib/digest/crc64.rb#13
Digest::CRC64::INIT_CRC = T.let(T.unsafe(nil), Integer)

# source://digest-crc//lib/digest/crc64.rb#11
Digest::CRC64::REFLECT_INPUT = T.let(T.unsafe(nil), TrueClass)

# Generated by `./pycrc.py --algorithm=table-driven --model=crc-64 --generate=c`
#
# source://digest-crc//lib/digest/crc64.rb#18
Digest::CRC64::TABLE = T.let(T.unsafe(nil), Array)

# source://digest-crc//lib/digest/crc64.rb#9
Digest::CRC64::WIDTH = T.let(T.unsafe(nil), Integer)

# source://digest-crc//lib/digest/crc64.rb#15
Digest::CRC64::XOR_MASK = T.let(T.unsafe(nil), Integer)

# Implements the CRC8 algorithm.
#
# source://digest-crc//lib/digest/crc8.rb#7
class Digest::CRC8 < ::Digest::CRC
  def update(_arg0); end
end

# @deprecated Please use {CRC8_1Wire} instead.
#
# source://digest-crc//lib/digest/crc8_1wire.rb#32
Digest::CRC81Wire = Digest::CRC8_1Wire

# source://digest-crc//lib/digest/crc8.rb#13
Digest::CRC8::INIT_CRC = T.let(T.unsafe(nil), Integer)

# source://digest-crc//lib/digest/crc8.rb#11
Digest::CRC8::REFLECT_INPUT = T.let(T.unsafe(nil), FalseClass)

# Generated by `./pycrc.py --algorithm=table-driven --model=crc-8 --generate=c`
#
# source://digest-crc//lib/digest/crc8.rb#16
Digest::CRC8::TABLE = T.let(T.unsafe(nil), Array)

# source://digest-crc//lib/digest/crc8.rb#9
Digest::CRC8::WIDTH = T.let(T.unsafe(nil), Integer)

# Implements the CRC8 1-Wire algorithm.
#
# source://digest-crc//lib/digest/crc8_1wire.rb#7
class Digest::CRC8_1Wire < ::Digest::CRC8
  def update(_arg0); end
end

# Generated by `./pycrc.py --algorithm=table-driven --model=dallas-1-wire --generate=c`
#
# source://digest-crc//lib/digest/crc8_1wire.rb#10
Digest::CRC8_1Wire::TABLE = T.let(T.unsafe(nil), Array)

# The initial value of the CRC checksum
#
# source://digest-crc//lib/digest/crc.rb#12
Digest::CRC::INIT_CRC = T.let(T.unsafe(nil), Integer)

# Define true or false whether the input direction is bit reversed or not of the CRC checksum
#
# source://digest-crc//lib/digest/crc.rb#21
Digest::CRC::REFLECT_INPUT = T.let(T.unsafe(nil), T.untyped)

# Default place holder CRC table
#
# source://digest-crc//lib/digest/crc.rb#24
Digest::CRC::TABLE = T.let(T.unsafe(nil), Array)

# The bit width of the CRC checksum
#
# source://digest-crc//lib/digest/crc.rb#18
Digest::CRC::WIDTH = T.let(T.unsafe(nil), Integer)

# The XOR mask to apply to the resulting CRC checksum
#
# source://digest-crc//lib/digest/crc.rb#15
Digest::CRC::XOR_MASK = T.let(T.unsafe(nil), Integer)
