# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `em-socksify` gem.
# Please instead update this file by running `bin/tapioca gem em-socksify`.


# source://em-socksify//lib/em-socksify/socksify.rb#1
module EventMachine; end

# source://em-socksify//lib/em-socksify/errors.rb#39
module EventMachine::Connectify
  # source://em-socksify//lib/em-socksify/connectify.rb#19
  def connect_hook; end

  # source://em-socksify//lib/em-socksify/connectify.rb#35
  def connect_receive_data(data); end

  # source://em-socksify//lib/em-socksify/connectify.rb#27
  def connect_unhook; end

  # source://em-socksify//lib/em-socksify/connectify.rb#4
  def connectify(host, port, username = T.unsafe(nil), password = T.unsafe(nil), &blk); end
end

# source://em-socksify//lib/em-socksify/connect.rb#3
module EventMachine::Connectify::CONNECT
  # source://em-socksify//lib/em-socksify/connect.rb#4
  def connect_send_handshake; end

  private

  # source://em-socksify//lib/em-socksify/connect.rb#17
  def connect_parse_response; end
end

# source://em-socksify//lib/em-socksify/errors.rb#40
class EventMachine::Connectify::CONNECTError < ::Exception; end

class EventMachine::ConnectionError < ::RuntimeError; end
class EventMachine::ConnectionNotBound < ::RuntimeError; end
module EventMachine::HttpServer; end
class EventMachine::InvalidSignature < ::RuntimeError; end
class EventMachine::NoHandlerForAcceptedConnection < ::RuntimeError; end

# source://em-socksify//lib/em-socksify/socksify.rb#3
module EventMachine::Socksify
  # source://em-socksify//lib/em-socksify/socksify.rb#20
  def socks_hook; end

  # source://em-socksify//lib/em-socksify/socksify.rb#40
  def socks_receive_data(data); end

  # source://em-socksify//lib/em-socksify/socksify.rb#32
  def socks_unhook(ip = T.unsafe(nil)); end

  # source://em-socksify//lib/em-socksify/socksify.rb#4
  def socksify(host, port, username = T.unsafe(nil), password = T.unsafe(nil), version = T.unsafe(nil), &blk); end
end

# source://em-socksify//lib/em-socksify/socks5.rb#4
module EventMachine::Socksify::SOCKS5
  # source://em-socksify//lib/em-socksify/socks5.rb#33
  def socks_send_authentication; end

  # source://em-socksify//lib/em-socksify/socks5.rb#15
  def socks_send_connect_request; end

  # source://em-socksify//lib/em-socksify/socks5.rb#5
  def socks_send_handshake; end

  private

  # source://em-socksify//lib/em-socksify/socks5.rb#107
  def socks_methods; end

  # parses socks 5 server responses as specified
  # on http://www.faqs.org/rfcs/rfc1928.html
  #
  # source://em-socksify//lib/em-socksify/socks5.rb#46
  def socks_parse_response; end
end

# source://em-socksify//lib/em-socksify/errors.rb#4
class EventMachine::Socksify::SOCKSError < ::Exception
  class << self
    # source://em-socksify//lib/em-socksify/errors.rb#5
    def define(message); end

    # source://em-socksify//lib/em-socksify/errors.rb#22
    def for_response_code(code); end
  end
end

# source://em-socksify//lib/em-socksify/errors.rb#6
class EventMachine::Socksify::SOCKSError::AddressTypeNotSupported < ::EventMachine::Socksify::SOCKSError
  # source://em-socksify//lib/em-socksify/errors.rb#7
  def initialize; end
end

# source://em-socksify//lib/em-socksify/errors.rb#6
class EventMachine::Socksify::SOCKSError::CommandNotSupported < ::EventMachine::Socksify::SOCKSError
  # source://em-socksify//lib/em-socksify/errors.rb#7
  def initialize; end
end

# source://em-socksify//lib/em-socksify/errors.rb#6
class EventMachine::Socksify::SOCKSError::ConnectionRefused < ::EventMachine::Socksify::SOCKSError
  # source://em-socksify//lib/em-socksify/errors.rb#7
  def initialize; end
end

# source://em-socksify//lib/em-socksify/errors.rb#6
class EventMachine::Socksify::SOCKSError::HostUnreachable < ::EventMachine::Socksify::SOCKSError
  # source://em-socksify//lib/em-socksify/errors.rb#7
  def initialize; end
end

# source://em-socksify//lib/em-socksify/errors.rb#6
class EventMachine::Socksify::SOCKSError::NetworkUnreachable < ::EventMachine::Socksify::SOCKSError
  # source://em-socksify//lib/em-socksify/errors.rb#7
  def initialize; end
end

# source://em-socksify//lib/em-socksify/errors.rb#6
class EventMachine::Socksify::SOCKSError::NotAllowed < ::EventMachine::Socksify::SOCKSError
  # source://em-socksify//lib/em-socksify/errors.rb#7
  def initialize; end
end

# source://em-socksify//lib/em-socksify/errors.rb#6
class EventMachine::Socksify::SOCKSError::ServerFailure < ::EventMachine::Socksify::SOCKSError
  # source://em-socksify//lib/em-socksify/errors.rb#7
  def initialize; end
end

# source://em-socksify//lib/em-socksify/errors.rb#6
class EventMachine::Socksify::SOCKSError::TTLExpired < ::EventMachine::Socksify::SOCKSError
  # source://em-socksify//lib/em-socksify/errors.rb#7
  def initialize; end
end

class EventMachine::UnknownTimerFired < ::RuntimeError; end
class EventMachine::Unsupported < ::RuntimeError; end
