# typed: false

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `em-synchrony` gem.
# Please instead update this file by running `bin/tapioca gem em-synchrony`.


# source://em-synchrony//lib/em-synchrony/em-http.rb#7
module EventMachine
  class << self
    # A convenience method for wrapping a given block within
    # a Ruby Fiber such that async operations can be transparently
    # paused and resumed based on IO scheduling.
    # It detects whether EM is running or not.
    #
    # source://em-synchrony//lib/em-synchrony.rb#26
    def synchrony(blk = T.unsafe(nil), tail = T.unsafe(nil)); end
  end
end

class EventMachine::ConnectionError < ::RuntimeError; end
class EventMachine::ConnectionNotBound < ::RuntimeError; end

# source://em-synchrony//lib/em-synchrony/em-http.rb#8
module EventMachine::HTTPMethods
  # source://em-synchrony//lib/em-synchrony/em-http.rb#10
  def adelete(options = T.unsafe(nil), &blk); end

  # source://em-synchrony//lib/em-synchrony/em-http.rb#10
  def aget(options = T.unsafe(nil), &blk); end

  # source://em-synchrony//lib/em-synchrony/em-http.rb#10
  def ahead(options = T.unsafe(nil), &blk); end

  # source://em-synchrony//lib/em-synchrony/em-http.rb#10
  def aoptions(options = T.unsafe(nil), &blk); end

  # source://em-synchrony//lib/em-synchrony/em-http.rb#10
  def apatch(options = T.unsafe(nil), &blk); end

  # source://em-synchrony//lib/em-synchrony/em-http.rb#10
  def apost(options = T.unsafe(nil), &blk); end

  # source://em-synchrony//lib/em-synchrony/em-http.rb#10
  def aput(options = T.unsafe(nil), &blk); end

  # source://em-synchrony//lib/em-synchrony/em-http.rb#10
  def delete(options = T.unsafe(nil), &blk); end

  # source://em-synchrony//lib/em-synchrony/em-http.rb#10
  def get(options = T.unsafe(nil), &blk); end

  # source://em-synchrony//lib/em-synchrony/em-http.rb#10
  def head(options = T.unsafe(nil), &blk); end

  # source://em-synchrony//lib/em-synchrony/em-http.rb#10
  def options(options = T.unsafe(nil), &blk); end

  # source://em-synchrony//lib/em-synchrony/em-http.rb#10
  def patch(options = T.unsafe(nil), &blk); end

  # source://em-synchrony//lib/em-synchrony/em-http.rb#10
  def post(options = T.unsafe(nil), &blk); end

  # source://em-synchrony//lib/em-synchrony/em-http.rb#10
  def put(options = T.unsafe(nil), &blk); end
end

module EventMachine::HttpServer; end
class EventMachine::InvalidSignature < ::RuntimeError; end
class EventMachine::NoHandlerForAcceptedConnection < ::RuntimeError; end

# source://em-synchrony//lib/em-synchrony.rb#160
EventMachine::S = EventMachine::Synchrony

# source://em-synchrony//lib/em-synchrony/thread.rb#2
module EventMachine::Synchrony
  class << self
    # Fiber-aware EventMachine timer: wraps the passed in
    # block within a new fiber (new fiber on every invocation)
    # to allow you to continue using synchrony methods
    #
    # source://em-synchrony//lib/em-synchrony.rb#106
    def add_periodic_timer(interval, &blk); end

    # Fiber-aware EventMachine timer: wraps the passed in
    # block within a new fiber context such that you can
    # continue using synchrony methods
    #
    # source://em-synchrony//lib/em-synchrony.rb#96
    def add_timer(interval, &blk); end

    # Fiber-aware EM.defer
    #
    # source://em-synchrony//lib/em-synchrony.rb#120
    def defer(op = T.unsafe(nil), &blk); end

    # Routes to EM::Synchrony::Keyboard
    #
    # source://em-synchrony//lib/em-synchrony.rb#145
    def gets; end

    # Interrupt current fiber to give chance to other fibers
    #
    # source://em-synchrony//lib/em-synchrony.rb#151
    def interrupt; end

    # Fiber-aware EM.next_tick convenience function
    #
    # source://em-synchrony//lib/em-synchrony.rb#114
    def next_tick(&blk); end

    # Overrides behavior of kernel.sleep
    # Allows to add custom behavior, e.g. logging or redirection to
    # EM::Synchrony.sleep .
    # Calling 'sleep' in this function calls the actual kernel method.
    #
    # source://em-synchrony//lib/em-synchrony.rb#139
    def on_sleep(&blk); end

    # Fiber-aware sleep function using an EM timer
    #
    # Execution is stopped for specified amount of seconds
    # and then automatically resumed (just like regular sleep)
    # except without locking the reactor thread
    #
    # source://em-synchrony//lib/em-synchrony.rb#86
    def sleep(secs); end

    # sync is a close relative to inlineCallbacks from Twisted (Python)
    #
    # Synchrony.sync allows you to write sequential code while using asynchronous
    # or callback-based methods under the hood. Example:
    #
    # result = EM::Synchrony.sync EventMachine::HttpRequest.new(URL).get
    # p result.response
    #
    # As long as the asynchronous function returns a Deferrable object, which
    # has a "callback" and an "errback", the sync methond will automatically
    # yield and automatically resume your code (via Fibers) when the call
    # either succeeds or fails. You do not need to patch or modify the
    # Deferrable object, simply pass it to EM::Synchrony.sync
    #
    # source://em-synchrony//lib/em-synchrony.rb#63
    def sync(df); end

    # Fiber-aware EM.system
    #
    # source://em-synchrony//lib/em-synchrony.rb#128
    def system(cmd, *args); end
  end
end

# source://em-synchrony//lib/em-synchrony/connection_pool.rb#4
class EventMachine::Synchrony::ConnectionPool
  # @return [ConnectionPool] a new instance of ConnectionPool
  #
  # source://em-synchrony//lib/em-synchrony/connection_pool.rb#7
  def initialize(opts, &block); end

  # Choose first available connection and pass it to the supplied
  # block. This will block indefinitely until there is an available
  # connection to service the request.
  #
  # source://em-synchrony//lib/em-synchrony/connection_pool.rb#20
  def execute(async); end

  # Returns current pool utilization.
  #
  # @return [Hash] Current utilization.
  #
  # source://em-synchrony//lib/em-synchrony/connection_pool.rb#34
  def pool_status; end

  private

  # Acquire a lock on a connection and assign it to executing fiber
  # - if connection is available, pass it back to the calling block
  # - if pool is full, yield the current fiber until connection is available
  #
  # source://em-synchrony//lib/em-synchrony/connection_pool.rb#47
  def acquire(fiber); end

  # Allow the pool to behave as the underlying connection
  #
  # If the requesting method begins with "a" prefix, then
  # hijack the callbacks and errbacks to fire a connection
  # pool release whenever the request is complete. Otherwise
  # yield the connection within execute method and release
  # once it is complete (assumption: fiber will yield until
  # data is available, or request is complete)
  #
  # source://em-synchrony//lib/em-synchrony/connection_pool.rb#77
  def method_missing(method, *args, &blk); end

  # Release connection assigned to the supplied fiber and
  # resume any other pending connections (which will
  # immediately try to run acquire on the pool)
  #
  # source://em-synchrony//lib/em-synchrony/connection_pool.rb#60
  def release(fiber); end
end

# source://em-synchrony//lib/em-synchrony/iterator.rb#6
class EventMachine::Synchrony::Iterator < ::EventMachine::Iterator
  # synchronous iterator which will wait until all the
  # jobs are done before returning. Unfortunately this
  # means that you loose ability to choose concurrency
  # on the fly (see iterator documentation in EM)
  #
  # source://em-synchrony//lib/em-synchrony/iterator.rb#12
  def each(foreach = T.unsafe(nil), after = T.unsafe(nil), &blk); end

  # source://em-synchrony//lib/em-synchrony/iterator.rb#35
  def inject(obj, foreach = T.unsafe(nil), after = T.unsafe(nil), &block); end

  # source://em-synchrony//lib/em-synchrony/iterator.rb#24
  def map(&block); end
end

# source://em-synchrony//lib/em-synchrony/keyboard.rb#3
class EventMachine::Synchrony::Keyboard
  # Returns the value of attribute current_fiber.
  #
  # source://em-synchrony//lib/em-synchrony/keyboard.rb#4
  def current_fiber; end

  # source://em-synchrony//lib/em-synchrony/keyboard.rb#6
  def gets; end

  # Returns the value of attribute separator.
  #
  # source://em-synchrony//lib/em-synchrony/keyboard.rb#4
  def separator; end
end

# source://em-synchrony//lib/em-synchrony/keyboard.rb#14
class EventMachine::Synchrony::KeyboardHandler < ::EventMachine::Connection
  include ::EventMachine::Protocols::LineText2

  # @return [KeyboardHandler] a new instance of KeyboardHandler
  #
  # source://em-synchrony//lib/em-synchrony/keyboard.rb#17
  def initialize(keyboard); end

  # source://em-synchrony//lib/em-synchrony/keyboard.rb#21
  def receive_line(line); end

  # source://em-synchrony//lib/em-synchrony/keyboard.rb#28
  def unbind; end
end

# source://em-synchrony//lib/em-synchrony/em-multi.rb#3
class EventMachine::Synchrony::Multi
  include ::EventMachine::Deferrable

  # @return [Multi] a new instance of Multi
  #
  # source://em-synchrony//lib/em-synchrony/em-multi.rb#8
  def initialize; end

  # source://em-synchrony//lib/em-synchrony/em-multi.rb#13
  def add(name, conn); end

  # @return [Boolean]
  #
  # source://em-synchrony//lib/em-synchrony/em-multi.rb#23
  def finished?; end

  # source://em-synchrony//lib/em-synchrony/em-multi.rb#27
  def perform; end

  # Returns the value of attribute requests.
  #
  # source://em-synchrony//lib/em-synchrony/em-multi.rb#6
  def requests; end

  # Returns the value of attribute responses.
  #
  # source://em-synchrony//lib/em-synchrony/em-multi.rb#6
  def responses; end

  protected

  # source://em-synchrony//lib/em-synchrony/em-multi.rb#33
  def check_progress(fiber); end
end

# source://em-synchrony//lib/em-synchrony/tcpsocket.rb#3
class EventMachine::Synchrony::TCPSocket < ::EventMachine::Connection
  # @raise [IOError]
  #
  # source://em-synchrony//lib/em-synchrony/tcpsocket.rb#101
  def close; end

  # @return [Boolean]
  #
  # source://em-synchrony//lib/em-synchrony/tcpsocket.rb#39
  def closed?; end

  # EventMachine interface
  #
  # source://em-synchrony//lib/em-synchrony/tcpsocket.rb#112
  def connection_completed; end

  # source://em-synchrony//lib/em-synchrony/tcpsocket.rb#32
  def post_init; end

  # source://em-synchrony//lib/em-synchrony/tcpsocket.rb#85
  def read(num_bytes = T.unsafe(nil), dest = T.unsafe(nil)); end

  # @raise [ArgumentError]
  #
  # source://em-synchrony//lib/em-synchrony/tcpsocket.rb#89
  def read_nonblock(maxlen, dest = T.unsafe(nil)); end

  # source://em-synchrony//lib/em-synchrony/tcpsocket.rb#134
  def receive_data(data); end

  # source://em-synchrony//lib/em-synchrony/tcpsocket.rb#96
  def recv(num_bytes, flags = T.unsafe(nil)); end

  # @raise [IOError]
  #
  # source://em-synchrony//lib/em-synchrony/tcpsocket.rb#59
  def send(msg, flags); end

  # TCPSocket interface
  #
  # source://em-synchrony//lib/em-synchrony/tcpsocket.rb#57
  def setsockopt(level, name, value); end

  # direction must be one of :in or :out
  #
  # source://em-synchrony//lib/em-synchrony/tcpsocket.rb#49
  def sync(direction); end

  # Can't set a default value for reason (e.g. reason=nil), as in that case
  # EM fails to pass in the reason argument and you'll always get the default
  # value.
  #
  # source://em-synchrony//lib/em-synchrony/tcpsocket.rb#122
  def unbind(reason); end

  # Returns the value of attribute unbind_reason.
  #
  # source://em-synchrony//lib/em-synchrony/tcpsocket.rb#117
  def unbind_reason; end

  # source://em-synchrony//lib/em-synchrony/tcpsocket.rb#81
  def write(msg); end

  protected

  # @raise [ArgumentError]
  #
  # source://em-synchrony//lib/em-synchrony/tcpsocket.rb#142
  def handle_read(type, num_bytes, dest = T.unsafe(nil)); end

  # source://em-synchrony//lib/em-synchrony/tcpsocket.rb#212
  def read_data; end

  # source://em-synchrony//lib/em-synchrony/tcpsocket.rb#167
  def try_read_data; end

  # source://em-synchrony//lib/em-synchrony/tcpsocket.rb#223
  def write_data(data = T.unsafe(nil)); end

  class << self
    # source://em-synchrony//lib/em-synchrony/tcpsocket.rb#5
    def _old_new(sig, *args); end

    # source://em-synchrony//lib/em-synchrony/tcpsocket.rb#6
    def new(*args); end

    # source://em-synchrony//lib/em-synchrony/tcpsocket.rb#29
    def open(*args); end
  end
end

# source://em-synchrony//lib/em-synchrony/thread.rb#3
module EventMachine::Synchrony::Thread; end

# source://em-synchrony//lib/em-synchrony/thread.rb#70
class EventMachine::Synchrony::Thread::ConditionVariable
  # Creates a new ConditionVariable
  #
  # @return [ConditionVariable] a new instance of ConditionVariable
  #
  # source://em-synchrony//lib/em-synchrony/thread.rb#74
  def initialize; end

  # source://em-synchrony//lib/em-synchrony/thread.rb#94
  def _wakeup(mutex, fiber); end

  # Wakes up all threads waiting for this lock.
  #
  # source://em-synchrony//lib/em-synchrony/thread.rb#116
  def broadcast; end

  # Wakes up the first thread in line waiting for this lock.
  #
  # source://em-synchrony//lib/em-synchrony/thread.rb#106
  def signal; end

  # Releases the lock held in +mutex+ and waits; reacquires the lock on wakeup.
  #
  # If +timeout+ is given, this method returns after +timeout+ seconds passed,
  # even if no other thread doesn't signal.
  #
  # source://em-synchrony//lib/em-synchrony/thread.rb#84
  def wait(mutex, timeout = T.unsafe(nil)); end
end

# Fiber-aware drop-in replacements for thread objects
#
# source://em-synchrony//lib/em-synchrony/thread.rb#6
class EventMachine::Synchrony::Thread::Mutex
  # @return [Mutex] a new instance of Mutex
  #
  # source://em-synchrony//lib/em-synchrony/thread.rb#7
  def initialize; end

  # source://em-synchrony//lib/em-synchrony/thread.rb#24
  def _wakeup(fiber); end

  # @raise [FiberError]
  #
  # source://em-synchrony//lib/em-synchrony/thread.rb#12
  def lock; end

  # @return [Boolean]
  #
  # source://em-synchrony//lib/em-synchrony/thread.rb#20
  def locked?; end

  # source://em-synchrony//lib/em-synchrony/thread.rb#28
  def sleep(timeout = T.unsafe(nil)); end

  # source://em-synchrony//lib/em-synchrony/thread.rb#61
  def synchronize; end

  # source://em-synchrony//lib/em-synchrony/thread.rb#48
  def try_lock; end

  # @raise [FiberError]
  #
  # source://em-synchrony//lib/em-synchrony/thread.rb#52
  def unlock; end
end

class EventMachine::UnknownTimerFired < ::RuntimeError; end
class EventMachine::Unsupported < ::RuntimeError; end

# Monkey-patch
#
# source://em-synchrony//lib/em-synchrony/core_ext.rb#1
module Kernel
  # Monkey-patch
  #
  # source://em-synchrony//lib/em-synchrony/kernel.rb#13
  def sleep(*args); end

  private

  # source://em-synchrony//lib/em-synchrony/kernel.rb#6
  def orig_sleep(*_arg0); end

  class << self
    # Returns the value of attribute em_synchrony_sleep_hook.
    #
    # source://em-synchrony//lib/em-synchrony/kernel.rb#9
    def em_synchrony_sleep_hook; end

    # Sets the attribute em_synchrony_sleep_hook
    #
    # @param value the value to set the attribute em_synchrony_sleep_hook to.
    #
    # source://em-synchrony//lib/em-synchrony/kernel.rb#9
    def em_synchrony_sleep_hook=(_arg0); end
  end
end
