# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `inertia_rails` gem.
# Please instead update this file by running `bin/tapioca gem inertia_rails`.


class ActionDispatch::DebugExceptions
  include ::InertiaDebugExceptions
end

# source://inertia_rails//lib/patches/debug_exceptions/patch-5-1.rb#10
module InertiaDebugExceptions
  # source://inertia_rails//lib/patches/debug_exceptions/patch-5-1.rb#11
  def render_for_browser_request(request, wrapper); end
end

# Based on AbstractController::Callbacks::ActionFilter
# https://github.com/rails/rails/blob/v7.2.0/actionpack/lib/abstract_controller/callbacks.rb#L39
#
# source://inertia_rails//lib/inertia_rails/lazy.rb#1
module InertiaRails
  class << self
    # source://inertia_rails//lib/inertia_rails/inertia_rails.rb#13
    def configuration; end

    # @yield [CONFIGURATION]
    #
    # source://inertia_rails//lib/inertia_rails/inertia_rails.rb#9
    def configure; end

    # source://inertia_rails//lib/inertia_rails.rb#25
    def deprecator; end

    # source://inertia_rails//lib/inertia_rails/inertia_rails.rb#17
    def lazy(value = T.unsafe(nil), &block); end
  end
end

# source://inertia_rails//lib/inertia_rails/action_filter.rb#6
class InertiaRails::ActionFilter
  # @return [ActionFilter] a new instance of ActionFilter
  #
  # source://inertia_rails//lib/inertia_rails/action_filter.rb#7
  def initialize(conditional_key, actions); end

  # @return [Boolean]
  #
  # source://inertia_rails//lib/inertia_rails/action_filter.rb#12
  def match?(controller); end
end

# source://inertia_rails//lib/inertia_rails/inertia_rails.rb#7
InertiaRails::CONFIGURATION = T.let(T.unsafe(nil), InertiaRails::Configuration)

# source://inertia_rails//lib/inertia_rails/configuration.rb#4
class InertiaRails::Configuration
  # @return [Configuration] a new instance of Configuration
  #
  # source://inertia_rails//lib/inertia_rails/configuration.rb#32
  def initialize(controller: T.unsafe(nil), **attrs); end

  # source://inertia_rails//lib/inertia_rails/configuration.rb#41
  def bind_controller(controller); end

  # source://inertia_rails//lib/inertia_rails/configuration.rb#65
  def component_path_resolver(path:, action:); end

  # source://inertia_rails//lib/inertia_rails/configuration.rb#73
  def component_path_resolver=(value); end

  # source://inertia_rails//lib/inertia_rails/configuration.rb#70
  def deep_merge_shared_data; end

  # source://inertia_rails//lib/inertia_rails/configuration.rb#73
  def deep_merge_shared_data=(value); end

  # source://inertia_rails//lib/inertia_rails/configuration.rb#70
  def default_render; end

  # source://inertia_rails//lib/inertia_rails/configuration.rb#73
  def default_render=(value); end

  # source://inertia_rails//lib/inertia_rails/configuration.rb#45
  def freeze; end

  # source://inertia_rails//lib/inertia_rails/configuration.rb#70
  def layout; end

  # source://inertia_rails//lib/inertia_rails/configuration.rb#73
  def layout=(value); end

  # source://inertia_rails//lib/inertia_rails/configuration.rb#55
  def merge(config); end

  # source://inertia_rails//lib/inertia_rails/configuration.rb#50
  def merge!(config); end

  # source://inertia_rails//lib/inertia_rails/configuration.rb#70
  def ssr_enabled; end

  # source://inertia_rails//lib/inertia_rails/configuration.rb#73
  def ssr_enabled=(value); end

  # source://inertia_rails//lib/inertia_rails/configuration.rb#70
  def ssr_url; end

  # source://inertia_rails//lib/inertia_rails/configuration.rb#73
  def ssr_url=(value); end

  # source://inertia_rails//lib/inertia_rails/configuration.rb#70
  def version; end

  # source://inertia_rails//lib/inertia_rails/configuration.rb#73
  def version=(value); end

  # Internal: Finalizes the configuration for a specific controller.
  #
  # source://inertia_rails//lib/inertia_rails/configuration.rb#60
  def with_defaults(config); end

  protected

  # Returns the value of attribute controller.
  #
  # source://inertia_rails//lib/inertia_rails/configuration.rb#29
  def controller; end

  # Returns the value of attribute options.
  #
  # source://inertia_rails//lib/inertia_rails/configuration.rb#30
  def options; end

  private

  # source://inertia_rails//lib/inertia_rails/configuration.rb#84
  def evaluate_option(value); end

  class << self
    # source://inertia_rails//lib/inertia_rails/configuration.rb#78
    def default; end
  end
end

# source://inertia_rails//lib/inertia_rails/configuration.rb#5
InertiaRails::Configuration::DEFAULTS = T.let(T.unsafe(nil), Hash)

# source://inertia_rails//lib/inertia_rails/configuration.rb#27
InertiaRails::Configuration::OPTION_NAMES = T.let(T.unsafe(nil), Array)

# source://inertia_rails//lib/inertia_rails/controller.rb#6
module InertiaRails::Controller
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::InertiaRails::Controller::ClassMethods

  # source://inertia_rails//lib/inertia_rails/controller.rb#117
  def default_render; end

  # source://inertia_rails//lib/inertia_rails/controller.rb#125
  def redirect_to(options = T.unsafe(nil), response_options = T.unsafe(nil)); end

  private

  # source://inertia_rails//lib/inertia_rails/controller.rb#158
  def capture_inertia_errors(options); end

  # source://inertia_rails//lib/inertia_rails/controller.rb#137
  def inertia_configuration; end

  # source://inertia_rails//lib/inertia_rails/controller.rb#153
  def inertia_location(url); end

  # source://inertia_rails//lib/inertia_rails/controller.rb#141
  def inertia_shared_data; end

  # source://inertia_rails//lib/inertia_rails/controller.rb#132
  def inertia_view_assigns; end
end

# source://inertia_rails//lib/inertia_rails/controller.rb#17
module InertiaRails::Controller::ClassMethods
  # source://inertia_rails//lib/inertia_rails/controller.rb#50
  def _inertia_configuration; end

  # source://inertia_rails//lib/inertia_rails/controller.rb#57
  def _inertia_shared_data; end

  # source://inertia_rails//lib/inertia_rails/controller.rb#33
  def inertia_config(**attrs); end

  # source://inertia_rails//lib/inertia_rails/controller.rb#18
  def inertia_share(hash = T.unsafe(nil), **props, &block); end

  # source://inertia_rails//lib/inertia_rails/controller.rb#43
  def use_inertia_instance_props; end

  private

  # source://inertia_rails//lib/inertia_rails/controller.rb#77
  def extract_inertia_share_options(props); end

  # source://inertia_rails//lib/inertia_rails/controller.rb#103
  def filter_to_proc(filter); end

  # source://inertia_rails//lib/inertia_rails/controller.rb#71
  def push_to_inertia_share(**attrs, &block); end

  # source://inertia_rails//lib/inertia_rails/controller.rb#96
  def transform_inertia_share_option(options, from, to); end
end

# source://inertia_rails//lib/inertia_rails/engine.rb#5
class InertiaRails::Engine < ::Rails::Engine
  class << self
    private

    # source://activesupport/8.0.1/lib/active_support/class_attribute.rb#15
    def __class_attr___callbacks; end

    # source://activesupport/8.0.1/lib/active_support/class_attribute.rb#17
    def __class_attr___callbacks=(new_value); end
  end
end

# source://inertia_rails//lib/inertia_rails.rb#23
class InertiaRails::Error < ::StandardError; end

# source://inertia_rails//lib/inertia_rails/helper.rb#3
module InertiaRails::Helper
  # source://inertia_rails//lib/inertia_rails/helper.rb#8
  def inertia_headers; end

  # source://inertia_rails//lib/inertia_rails/helper.rb#4
  def inertia_ssr_head; end
end

# source://inertia_rails//lib/inertia_rails/lazy.rb#2
class InertiaRails::Lazy
  # @return [Lazy] a new instance of Lazy
  #
  # source://inertia_rails//lib/inertia_rails/lazy.rb#3
  def initialize(value = T.unsafe(nil), &block); end

  # source://inertia_rails//lib/inertia_rails/lazy.rb#8
  def call; end

  # source://inertia_rails//lib/inertia_rails/lazy.rb#12
  def to_proc; end
end

# source://inertia_rails//lib/inertia_rails/middleware.rb#2
class InertiaRails::Middleware
  # @return [Middleware] a new instance of Middleware
  #
  # source://inertia_rails//lib/inertia_rails/middleware.rb#3
  def initialize(app); end

  # source://inertia_rails//lib/inertia_rails/middleware.rb#7
  def call(env); end
end

# source://inertia_rails//lib/inertia_rails/middleware.rb#11
class InertiaRails::Middleware::InertiaRailsRequest
  # @return [InertiaRailsRequest] a new instance of InertiaRailsRequest
  #
  # source://inertia_rails//lib/inertia_rails/middleware.rb#12
  def initialize(app, env); end

  # source://inertia_rails//lib/inertia_rails/middleware.rb#17
  def response; end

  private

  # source://inertia_rails//lib/inertia_rails/middleware.rb#68
  def client_version; end

  # source://inertia_rails//lib/inertia_rails/middleware.rb#84
  def coerce_version(version); end

  # source://inertia_rails//lib/inertia_rails/middleware.rb#60
  def controller; end

  # source://inertia_rails//lib/inertia_rails/middleware.rb#93
  def copy_xsrf_to_csrf!; end

  # source://inertia_rails//lib/inertia_rails/middleware.rb#88
  def force_refresh(request); end

  # @return [Boolean]
  #
  # source://inertia_rails//lib/inertia_rails/middleware.rb#56
  def get?; end

  # @return [Boolean]
  #
  # source://inertia_rails//lib/inertia_rails/middleware.rb#48
  def inertia_non_post_redirect?(status); end

  # @return [Boolean]
  #
  # source://inertia_rails//lib/inertia_rails/middleware.rb#72
  def inertia_request?; end

  # @return [Boolean]
  #
  # source://inertia_rails//lib/inertia_rails/middleware.rb#32
  def keep_inertia_errors?(status); end

  # @return [Boolean]
  #
  # source://inertia_rails//lib/inertia_rails/middleware.rb#44
  def non_get_redirectable_method?; end

  # @return [Boolean]
  #
  # source://inertia_rails//lib/inertia_rails/middleware.rb#40
  def redirect_status?(status); end

  # source://inertia_rails//lib/inertia_rails/middleware.rb#64
  def request_method; end

  # source://inertia_rails//lib/inertia_rails/middleware.rb#80
  def server_version; end

  # @return [Boolean]
  #
  # source://inertia_rails//lib/inertia_rails/middleware.rb#52
  def stale_inertia_get?; end

  # @return [Boolean]
  #
  # source://inertia_rails//lib/inertia_rails/middleware.rb#36
  def stale_inertia_request?; end

  # @return [Boolean]
  #
  # source://inertia_rails//lib/inertia_rails/middleware.rb#76
  def version_stale?; end
end

# source://inertia_rails//lib/inertia_rails/renderer.rb#6
class InertiaRails::Renderer
  # @return [Renderer] a new instance of Renderer
  #
  # source://inertia_rails//lib/inertia_rails/renderer.rb#15
  def initialize(component, controller, request, response, render_method, props: T.unsafe(nil), view_data: T.unsafe(nil), deep_merge: T.unsafe(nil)); end

  # Returns the value of attribute component.
  #
  # source://inertia_rails//lib/inertia_rails/renderer.rb#7
  def component; end

  # Returns the value of attribute configuration.
  #
  # source://inertia_rails//lib/inertia_rails/renderer.rb#7
  def configuration; end

  # Returns the value of attribute controller.
  #
  # source://inertia_rails//lib/inertia_rails/renderer.rb#7
  def controller; end

  # Returns the value of attribute props.
  #
  # source://inertia_rails//lib/inertia_rails/renderer.rb#7
  def props; end

  # source://inertia_rails//lib/inertia_rails/renderer.rb#27
  def render; end

  # source://inertia_rails//lib/inertia_rails/renderer.rb#7
  def view_data; end

  private

  # source://inertia_rails//lib/inertia_rails/renderer.rb#70
  def computed_props; end

  # source://inertia_rails//lib/inertia_rails/renderer.rb#96
  def deep_transform_values(hash, proc); end

  # source://inertia_rails//lib/inertia_rails/renderer.rb#52
  def layout; end

  # Cast props to symbol keyed hash before merging so that we have a consistent data structure and
  # avoid duplicate keys after merging.
  #
  # Functionally, this permits using either string or symbol keys in the controller. Since the results
  # is cast to json, we should treat string/symbol keys as identical.
  #
  # source://inertia_rails//lib/inertia_rails/renderer.rb#66
  def merge_props(shared_data, props); end

  # source://inertia_rails//lib/inertia_rails/renderer.rb#87
  def page; end

  # source://inertia_rails//lib/inertia_rails/renderer.rb#102
  def partial_keys; end

  # source://inertia_rails//lib/inertia_rails/renderer.rb#44
  def render_ssr; end

  # @return [Boolean]
  #
  # source://inertia_rails//lib/inertia_rails/renderer.rb#106
  def rendering_partial_component?; end

  # source://inertia_rails//lib/inertia_rails/renderer.rb#110
  def resolve_component(component); end

  # source://inertia_rails//lib/inertia_rails/renderer.rb#57
  def shared_data; end
end
