# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `shortener` gem.
# Please instead update this file by running `bin/tapioca gem shortener`.


# source://shortener//lib/shortener.rb#3
module Shortener
  # source://shortener//lib/shortener.rb#45
  def auto_clean_url; end

  # source://shortener//lib/shortener.rb#45
  def auto_clean_url=(val); end

  # source://shortener//lib/shortener.rb#25
  def charset; end

  # source://shortener//lib/shortener.rb#25
  def charset=(val); end

  # source://shortener//lib/shortener.rb#29
  def default_redirect; end

  # source://shortener//lib/shortener.rb#29
  def default_redirect=(val); end

  # source://shortener//lib/shortener.rb#33
  def forbidden_keys; end

  # source://shortener//lib/shortener.rb#33
  def forbidden_keys=(val); end

  # source://shortener//lib/shortener.rb#37
  def ignore_robots; end

  # source://shortener//lib/shortener.rb#37
  def ignore_robots=(val); end

  # source://shortener//lib/shortener.rb#41
  def persist_retries; end

  # source://shortener//lib/shortener.rb#41
  def persist_retries=(val); end

  # source://shortener//lib/shortener.rb#14
  def subdomain; end

  # source://shortener//lib/shortener.rb#14
  def subdomain=(val); end

  # source://shortener//lib/shortener.rb#18
  def unique_key_length; end

  # source://shortener//lib/shortener.rb#18
  def unique_key_length=(val); end

  class << self
    # source://shortener//lib/shortener.rb#45
    def auto_clean_url; end

    # source://shortener//lib/shortener.rb#45
    def auto_clean_url=(val); end

    # source://shortener//lib/shortener.rb#25
    def charset; end

    # source://shortener//lib/shortener.rb#25
    def charset=(val); end

    # source://shortener//lib/shortener.rb#29
    def default_redirect; end

    # source://shortener//lib/shortener.rb#29
    def default_redirect=(val); end

    # source://shortener//lib/shortener.rb#33
    def forbidden_keys; end

    # source://shortener//lib/shortener.rb#33
    def forbidden_keys=(val); end

    # source://shortener//lib/shortener.rb#37
    def ignore_robots; end

    # source://shortener//lib/shortener.rb#37
    def ignore_robots=(val); end

    # source://shortener//lib/shortener.rb#48
    def key_chars; end

    # source://shortener//lib/shortener.rb#41
    def persist_retries; end

    # source://shortener//lib/shortener.rb#41
    def persist_retries=(val); end

    # source://shortener//lib/shortener.rb#14
    def subdomain; end

    # source://shortener//lib/shortener.rb#14
    def subdomain=(val); end

    # source://shortener//lib/shortener.rb#18
    def unique_key_length; end

    # source://shortener//lib/shortener.rb#18
    def unique_key_length=(val); end
  end
end

# source://shortener//lib/shortener/active_record_extension.rb#1
module Shortener::ActiveRecordExtension
  # source://shortener//lib/shortener/active_record_extension.rb#2
  def has_shortened_urls; end
end

# source://shortener//lib/shortener.rb#8
Shortener::CHARSETS = T.let(T.unsafe(nil), Hash)

# source://shortener//lib/shortener/engine.rb#7
class Shortener::Engine < ::Rails::Engine; end

# source://shortener//lib/shortener/railtie.rb#4
class Shortener::Railtie < ::Rails::Railtie; end

class Shortener::Record < ::ActiveRecord::Base
  include ::Shortener::Record::GeneratedAttributeMethods
  include ::Shortener::Record::GeneratedAssociationMethods

  class << self
    private

    def __class_attr__validators; end
    def __class_attr__validators=(new_value); end
    def __class_attr_defined_enums; end
    def __class_attr_defined_enums=(new_value); end
  end
end

module Shortener::Record::GeneratedAssociationMethods; end
module Shortener::Record::GeneratedAttributeMethods; end

# The Shorten URL Interceptor is a mail interceptor which shortens any URLs
# in generated emails.
#
# Usage:
#
#   class MyMailer < ActionMailer::Base
#     register_interceptor Shortener::ShortenUrlInterceptor.new
#   end
#
# source://shortener//lib/shortener/shorten_url_interceptor.rb#13
class Shortener::ShortenUrlInterceptor
  # @return [ShortenUrlInterceptor] a new instance of ShortenUrlInterceptor
  #
  # source://shortener//lib/shortener/shorten_url_interceptor.rb#23
  def initialize(opts = T.unsafe(nil)); end

  # source://shortener//lib/shortener/shorten_url_interceptor.rb#29
  def delivering_email(email); end

  protected

  # source://shortener//lib/shortener/shorten_url_interceptor.rb#41
  def shorten_url(url); end

  class << self
    # source://shortener//lib/shortener/shorten_url_interceptor.rb#54
    def infer_base_url; end
  end
end

# source://shortener//lib/shortener/shorten_url_interceptor.rb#18
Shortener::ShortenUrlInterceptor::DEFAULT_LENGTH_THRESHOLD = T.let(T.unsafe(nil), Integer)

# source://shortener//lib/shortener/shorten_url_interceptor.rb#15
Shortener::ShortenUrlInterceptor::DEFAULT_NOT_SHORTEN = T.let(T.unsafe(nil), Array)

# source://shortener//lib/shortener/shorten_url_interceptor.rb#21
Shortener::ShortenUrlInterceptor::MIME_TYPES = T.let(T.unsafe(nil), Array)

# source://shortener//lib/shortener/shorten_url_interceptor.rb#20
Shortener::ShortenUrlInterceptor::URL_REGEX = T.let(T.unsafe(nil), Regexp)

class Shortener::ShortenedUrl < ::Shortener::Record
  include ::Shortener::ShortenedUrl::GeneratedAttributeMethods
  include ::Shortener::ShortenedUrl::GeneratedAssociationMethods

  def autosave_associated_records_for_owner(*args); end
  def custom_key; end
  def custom_key=(_arg0); end
  def increment_usage_count; end
  def to_param; end

  private

  def generate_unique_key(retries = T.unsafe(nil)); end

  class << self
    def clean_url(url); end
    def extract_token(token_str); end
    def fetch_with_token(token: T.unsafe(nil), additional_params: T.unsafe(nil), track: T.unsafe(nil)); end
    def generate(destination_url, owner: T.unsafe(nil), custom_key: T.unsafe(nil), expires_at: T.unsafe(nil), fresh: T.unsafe(nil), category: T.unsafe(nil)); end
    def generate!(destination_url, owner: T.unsafe(nil), custom_key: T.unsafe(nil), expires_at: T.unsafe(nil), fresh: T.unsafe(nil), category: T.unsafe(nil)); end
    def merge_params_to_url(url: T.unsafe(nil), params: T.unsafe(nil)); end
    def unexpired(*args, **_arg1); end
    def unique_key_candidate; end

    private

    def __class_attr___callbacks; end
    def __class_attr___callbacks=(new_value); end
    def __class_attr__reflections; end
    def __class_attr__reflections=(new_value); end
    def __class_attr__validators; end
    def __class_attr__validators=(new_value); end
    def __class_attr_defined_enums; end
    def __class_attr_defined_enums=(new_value); end
  end
end

module Shortener::ShortenedUrl::GeneratedAssociationMethods
  def owner; end
  def owner=(value); end
  def owner_changed?; end
  def owner_previously_changed?; end
  def reload_owner; end
  def reset_owner; end
end

module Shortener::ShortenedUrl::GeneratedAttributeMethods; end
Shortener::ShortenedUrl::REGEX_LINK_HAS_PROTOCOL = T.let(T.unsafe(nil), Regexp)

class Shortener::ShortenedUrlsController < ::ActionController::Metal
  include ::ActionController::StrongParameters
  include ::AbstractController::Logger
  include ::ActiveSupport::Benchmarkable
  include ::ActionDispatch::Routing::PolymorphicRoutes
  include ::ActionDispatch::Routing::UrlFor
  include ::AbstractController::UrlFor
  include ::ActionController::UrlFor
  include ::ActionController::Redirecting
  include ::ActionController::Instrumentation
  include ::Shortener
  extend ::AbstractController::UrlFor::ClassMethods
  extend ::ActionController::Instrumentation::ClassMethods

  def default_url_options; end
  def default_url_options=(_arg0); end
  def default_url_options?; end
  def logger; end
  def logger=(value); end
  def raise_on_open_redirects; end
  def raise_on_open_redirects=(val); end
  def show; end

  class << self
    def _routes; end
    def default_url_options; end
    def default_url_options=(value); end
    def default_url_options?; end
    def logger; end
    def logger=(value); end
    def raise_on_open_redirects; end
    def raise_on_open_redirects=(val); end

    private

    def __class_attr_default_url_options; end
    def __class_attr_default_url_options=(new_value); end
    def __class_attr_middleware_stack; end
    def __class_attr_middleware_stack=(new_value); end
  end
end

module Shortener::ShortenerHelper
  def short_url(url, owner: T.unsafe(nil), custom_key: T.unsafe(nil), expires_at: T.unsafe(nil), fresh: T.unsafe(nil), category: T.unsafe(nil), url_options: T.unsafe(nil)); end
end
