# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `voight_kampff` gem.
# Please instead update this file by running `bin/tapioca gem voight_kampff`.


class ActionDispatch::Request
  include ::VoightKampff::Methods
end

class Rack::Request
  include ::VoightKampff::Methods
end

# source://voight_kampff//lib/voight_kampff/test.rb#1
module VoightKampff
  class << self
    # @return [Boolean]
    #
    # source://voight_kampff//lib/voight_kampff.rb#17
    def bot?(user_agent_string); end

    # @return [Boolean]
    #
    # source://voight_kampff//lib/voight_kampff.rb#13
    def human?(user_agent_string); end

    # @return [Boolean]
    #
    # source://voight_kampff//lib/voight_kampff.rb#17
    def replicant?(user_agent_string); end

    # source://voight_kampff//lib/voight_kampff.rb#8
    def root; end

    private

    # source://voight_kampff//lib/voight_kampff.rb#24
    def test(user_agent_string); end
  end
end

# source://voight_kampff//lib/voight_kampff/engine.rb#2
class VoightKampff::Engine < ::Rails::Engine
  class << self
    private

    # source://activesupport/8.0.1/lib/active_support/class_attribute.rb#15
    def __class_attr___callbacks; end

    # source://activesupport/8.0.1/lib/active_support/class_attribute.rb#17
    def __class_attr___callbacks=(new_value); end
  end
end

# source://voight_kampff//lib/voight_kampff/methods.rb#1
module VoightKampff::Methods
  # @return [Boolean]
  #
  # source://voight_kampff//lib/voight_kampff/methods.rb#6
  def bot?; end

  # @return [Boolean]
  #
  # source://voight_kampff//lib/voight_kampff/methods.rb#2
  def human?; end

  # @return [Boolean]
  #
  # source://voight_kampff//lib/voight_kampff/methods.rb#6
  def replicant?; end
end

# source://voight_kampff//lib/voight_kampff/test.rb#2
class VoightKampff::Test
  # @return [Test] a new instance of Test
  #
  # source://voight_kampff//lib/voight_kampff/test.rb#7
  def initialize(user_agent_string); end

  # source://voight_kampff//lib/voight_kampff/test.rb#11
  def agent; end

  # @return [Boolean]
  #
  # source://voight_kampff//lib/voight_kampff/test.rb#19
  def bot?; end

  # @return [Boolean]
  #
  # source://voight_kampff//lib/voight_kampff/test.rb#15
  def human?; end

  # @return [Boolean]
  #
  # source://voight_kampff//lib/voight_kampff/test.rb#19
  def replicant?; end

  # Returns the value of attribute user_agent_string.
  #
  # source://voight_kampff//lib/voight_kampff/test.rb#5
  def user_agent_string; end

  # Sets the attribute user_agent_string
  #
  # @param value the value to set the attribute user_agent_string to.
  #
  # source://voight_kampff//lib/voight_kampff/test.rb#5
  def user_agent_string=(_arg0); end

  private

  # source://voight_kampff//lib/voight_kampff/test.rb#46
  def crawler_regexp; end

  # source://voight_kampff//lib/voight_kampff/test.rb#56
  def crawlers; end

  # source://voight_kampff//lib/voight_kampff/test.rb#26
  def lookup_paths; end

  # source://voight_kampff//lib/voight_kampff/test.rb#39
  def matching_crawler; end

  # source://voight_kampff//lib/voight_kampff/test.rb#35
  def preferred_path; end
end

# source://voight_kampff//lib/voight_kampff/test.rb#3
VoightKampff::Test::CRAWLERS_FILENAME = T.let(T.unsafe(nil), String)
