inherit_mode:
    merge:
        - Exclude

require:
    - standard
    - rubocop-performance

inherit_gem:
    standard: config/base.yml
    standard-performance: config/base.yml
    standard-custom: config/base.yml

inherit_from:
    - .rubocop/rails.yml
    - .rubocop/rspec.yml
    - .rubocop/strict.yml

AllCops:
    NewCops: disable
    SuggestExtensions: false
    TargetRubyVersion: 3.2
