inherit_mode:
    merge:
        - Exclude

plugins:
    - rubocop-performance

inherit_from:
    - .rubocop/rails.yml
    - .rubocop/rspec.yml
    - .rubocop/strict.yml

AllCops:
    NewCops: disable
    SuggestExtensions: false
    TargetRubyVersion: 3.2
    Exclude:
        - "db/migrate/*"
        - "sorbet/*"

Lint/UnderscorePrefixedVariableName:
    Enabled: false

Style/GlobalStdStream:
    Enabled: false

Style/StringLiterals:
    EnforcedStyle: double_quotes

Layout/SpaceInsideHashLiteralBraces:
    EnforcedStyle: space
