inherit_mode:
    merge:
        - Exclude

plugins:
    - rubocop-performance

inherit_from:
    - .rubocop/rails.yml
    - .rubocop/rspec.yml
    - .rubocop/strict.yml
    - node_modules/@prettier/plugin-ruby/rubocop.yml

AllCops:
    NewCops: disable
    SuggestExtensions: false
    TargetRubyVersion: 3.2
    Exclude:
        - "db/migrate/*"
        - "sorbet/*"

Lint/UnderscorePrefixedVariableName:
    Enabled: false

Style/GlobalStdStream:
    Enabled: false

Style/StringLiterals:
    EnforcedStyle: double_quotes

Layout/SpaceInsideHashLiteralBraces:
    EnforcedStyle: space

Layout/IndentationWidth:
    Enable: true
    Width: 2

Metrics/AbcSize:
    Max: 50

Metrics/MethodLength:
    Max: 50

Style/Documentation:
    Enabled: false

Style/FrozenStringLiteralComment:
    Enabled: false

Naming/PredicatePrefix:
    Enabled: false

Layout/LineLength:
    Enabled: false
