# fly.toml app configuration file generated for sway on 2024-06-07T10:24:01-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sway'
primary_region = 'mia'
console_command = '/rails/bin/rails console'

[build]
  image = 'ghcr.io/plebeian-technology/sway:latest'
  #dockerfile = "docker/dockerfiles/production.dockerfile"
  #ignorefile = "docker/dockerfiles/production.dockerfile.dockerignore"

[[mounts]]
  source = 'prodswaysqlite'
  destination = '/rails/storage'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 3

  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/up'

[checks]
  [checks.status]
    port = 3000
    type = 'http'
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/up'
    protocol = 'http'
    tls_skip_verify = false

    [checks.status.headers]
      X-Forwarded-Proto = 'https'

[[vm]]
  #memory = '256mb'
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
