module Scraper
    module Maryland
        class LegislatorVotes
            @bill: untyped

            @sway_locale: untyped

            @roll_call_number: untyped

            @roll_call_chamber: untyped

            @result: untyped

            include ApiConnector

            def initialize: (untyped bill, untyped roll_call_number, untyped roll_call_chamber) -> void

            def content_type: -> "application/pdf"

            # r = Faraday.get('https://mgaleg.maryland.gov/2025RS/votes/house/0549.pdf').body
            def do_request: -> untyped

            def do_process: -> (::Array[untyped] | untyped)

            private

            def result: -> untyped

            def endpoint: -> ::String

            def roll: -> untyped
        end
    end
end
