interface ::_RbsRailsPathHelpers
    def rails_mailers_path: (*untyped) -> ::String
    def rails_info_properties_path: (*untyped) -> ::String
    def rails_info_routes_path: (*untyped) -> ::String
    def rails_info_notes_path: (*untyped) -> ::String
    def rails_info_path: (*untyped) -> ::String
    def bill_of_the_week_schedule_update_path: (*untyped) -> ::String
    def root_path: (*untyped) -> ::String
    def invite_path: (*untyped) -> ::String
    def invites_path: (*untyped) -> ::String
    def rails_health_check_path: (*untyped) -> ::String
    def bills_path: (*untyped) -> ::String
    def new_bill_path: (*untyped) -> ::String
    def edit_bill_path: (*untyped) -> ::String
    def bill_path: (*untyped) -> ::String
    def bill_of_the_week_index_path: (*untyped) -> ::String
    def bill_of_the_week_schedule_path: (*untyped) -> ::String
    def bill_score_path: (*untyped) -> ::String
    def bill_score_district_path: (*untyped) -> ::String
    def districts_path: (*untyped) -> ::String
    def influence_index_path: (*untyped) -> ::String
    def legislators_path: (*untyped) -> ::String
    def legislator_path: (*untyped) -> ::String
    def legislator_votes_path: (*untyped) -> ::String
    def legislator_vote_path: (*untyped) -> ::String
    def user_legislator_emails_path: (*untyped) -> ::String
    def organizations_path: (*untyped) -> ::String
    def organization_path: (*untyped) -> ::String
    def organization_bill_positions_path: (*untyped) -> ::String
    def organization_bill_position_path: (*untyped) -> ::String
    def sway_locales_path: (*untyped) -> ::String
    def sway_locale_path: (*untyped) -> ::String
    def accept_organization_membership_invite_path: (*untyped) -> ::String
    def organization_membership_invites_path: (*untyped) -> ::String
    def organization_membership_path: (*untyped) -> ::String
    def organization_positions_path: (*untyped) -> ::String
    def new_organization_position_path: (*untyped) -> ::String
    def organization_position_path: (*untyped) -> ::String
    def organization_position_changes_path: (*untyped) -> ::String
    def organization_position_change_path: (*untyped) -> ::String
    def user_districts_path: (*untyped) -> ::String
    def user_legislators_path: (*untyped) -> ::String
    def user_legislator_scores_path: (*untyped) -> ::String
    def user_legislator_score_path: (*untyped) -> ::String
    def user_votes_path: (*untyped) -> ::String
    def user_vote_path: (*untyped) -> ::String
    def buckets_assets_path: (*untyped) -> ::String
    def settings_notifications_path: (*untyped) -> ::String
    def notifications_path: (*untyped) -> ::String
    def notifications_push_notifications_path: (*untyped) -> ::String
    def destroy_notifications_push_notification_subscriptions_path: (*untyped) -> ::String
    def notifications_push_notification_subscriptions_path: (*untyped) -> ::String
    def phone_verification_index_path: (*untyped) -> ::String
    def phone_verification_path: (*untyped) -> ::String
    def email_verification_index_path: (*untyped) -> ::String
    def email_verification_path: (*untyped) -> ::String
    def api_keys_path: (*untyped) -> ::String
    def api_key_path: (*untyped) -> ::String
    def sway_registration_index_path: (*untyped) -> ::String
    def callback_users_webauthn_sessions_path: (*untyped) -> ::String
    def users_webauthn_sessions_path: (*untyped) -> ::String
    def users_webauthn_session_path: (*untyped) -> ::String
    def callback_users_webauthn_registration_index_path: (*untyped) -> ::String
    def users_webauthn_registration_index_path: (*untyped) -> ::String
    def users_details_path: (*untyped) -> ::String
    def users_organization_memberships_path: (*untyped) -> ::String
    def rails_service_blob_path: (*untyped) -> ::String
    def rails_service_blob_proxy_path: (*untyped) -> ::String
    def rails_blob_representation_path: (*untyped) -> ::String
    def rails_blob_representation_proxy_path: (*untyped) -> ::String
    def rails_disk_service_path: (*untyped) -> ::String
    def update_rails_disk_service_path: (*untyped) -> ::String
    def rails_direct_uploads_path: (*untyped) -> ::String
    def rails_representation_path: (*untyped) -> ::String
    def rails_blob_path: (*untyped) -> ::String
    def rails_storage_proxy_path: (*untyped) -> ::String
    def rails_storage_redirect_path: (*untyped) -> ::String
    def rails_mailers_url: (*untyped) -> ::String
    def rails_info_properties_url: (*untyped) -> ::String
    def rails_info_routes_url: (*untyped) -> ::String
    def rails_info_notes_url: (*untyped) -> ::String
    def rails_info_url: (*untyped) -> ::String
    def bill_of_the_week_schedule_update_url: (*untyped) -> ::String
    def root_url: (*untyped) -> ::String
    def invite_url: (*untyped) -> ::String
    def invites_url: (*untyped) -> ::String
    def rails_health_check_url: (*untyped) -> ::String
    def bills_url: (*untyped) -> ::String
    def new_bill_url: (*untyped) -> ::String
    def edit_bill_url: (*untyped) -> ::String
    def bill_url: (*untyped) -> ::String
    def bill_of_the_week_index_url: (*untyped) -> ::String
    def bill_of_the_week_schedule_url: (*untyped) -> ::String
    def bill_score_url: (*untyped) -> ::String
    def bill_score_district_url: (*untyped) -> ::String
    def districts_url: (*untyped) -> ::String
    def influence_index_url: (*untyped) -> ::String
    def legislators_url: (*untyped) -> ::String
    def legislator_url: (*untyped) -> ::String
    def legislator_votes_url: (*untyped) -> ::String
    def legislator_vote_url: (*untyped) -> ::String
    def user_legislator_emails_url: (*untyped) -> ::String
    def organizations_url: (*untyped) -> ::String
    def organization_url: (*untyped) -> ::String
    def organization_bill_positions_url: (*untyped) -> ::String
    def organization_bill_position_url: (*untyped) -> ::String
    def sway_locales_url: (*untyped) -> ::String
    def sway_locale_url: (*untyped) -> ::String
    def accept_organization_membership_invite_url: (*untyped) -> ::String
    def organization_membership_invites_url: (*untyped) -> ::String
    def organization_membership_url: (*untyped) -> ::String
    def organization_positions_url: (*untyped) -> ::String
    def new_organization_position_url: (*untyped) -> ::String
    def organization_position_url: (*untyped) -> ::String
    def organization_position_changes_url: (*untyped) -> ::String
    def organization_position_change_url: (*untyped) -> ::String
    def user_districts_url: (*untyped) -> ::String
    def user_legislators_url: (*untyped) -> ::String
    def user_legislator_scores_url: (*untyped) -> ::String
    def user_legislator_score_url: (*untyped) -> ::String
    def user_votes_url: (*untyped) -> ::String
    def user_vote_url: (*untyped) -> ::String
    def buckets_assets_url: (*untyped) -> ::String
    def settings_notifications_url: (*untyped) -> ::String
    def notifications_url: (*untyped) -> ::String
    def notifications_push_notifications_url: (*untyped) -> ::String
    def destroy_notifications_push_notification_subscriptions_url: (*untyped) -> ::String
    def notifications_push_notification_subscriptions_url: (*untyped) -> ::String
    def phone_verification_index_url: (*untyped) -> ::String
    def phone_verification_url: (*untyped) -> ::String
    def email_verification_index_url: (*untyped) -> ::String
    def email_verification_url: (*untyped) -> ::String
    def api_keys_url: (*untyped) -> ::String
    def api_key_url: (*untyped) -> ::String
    def sway_registration_index_url: (*untyped) -> ::String
    def callback_users_webauthn_sessions_url: (*untyped) -> ::String
    def users_webauthn_sessions_url: (*untyped) -> ::String
    def users_webauthn_session_url: (*untyped) -> ::String
    def callback_users_webauthn_registration_index_url: (*untyped) -> ::String
    def users_webauthn_registration_index_url: (*untyped) -> ::String
    def users_details_url: (*untyped) -> ::String
    def users_organization_memberships_url: (*untyped) -> ::String
    def rails_service_blob_url: (*untyped) -> ::String
    def rails_service_blob_proxy_url: (*untyped) -> ::String
    def rails_blob_representation_url: (*untyped) -> ::String
    def rails_blob_representation_proxy_url: (*untyped) -> ::String
    def rails_disk_service_url: (*untyped) -> ::String
    def update_rails_disk_service_url: (*untyped) -> ::String
    def rails_direct_uploads_url: (*untyped) -> ::String
    def rails_representation_url: (*untyped) -> ::String
    def rails_blob_url: (*untyped) -> ::String
    def rails_storage_proxy_url: (*untyped) -> ::String
    def rails_storage_redirect_url: (*untyped) -> ::String
end

module ::ActionController
    class ::ActionController::Base
        include ::_RbsRailsPathHelpers
    end
end
