# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Shortener::ShortenedUrlsController`.
# Please instead update this file by running `bin/tapioca dsl Shortener::ShortenedUrlsController`.

class Shortener::ShortenedUrlsController
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
