# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ApiKeyAuthenticatable`.
# Please instead update this file by running `bin/tapioca dsl ApiKeyAuthenticatable`.


module ApiKeyAuthenticatable
  mixes_in_class_methods ::ActionController::HttpAuthentication::Basic::ControllerMethods::ClassMethods
end
