class LegislatorsController < ApplicationController
    @legislator: untyped

    # GET /legislators or /legislators.json
    def index: -> untyped

    def show: -> untyped

    private

    def set_legislator: -> untyped

    def json_legislators: -> untyped

    # Only allow a list of trusted parameters through.
    def legislator_params: -> untyped
end
