class OrganizationsController < ApplicationController
    @bill: untyped

    def index: -> untyped

    def show: -> untyped

    def create: -> untyped

    private

    def set_bill: -> untyped

    def organizations_params: -> untyped

    def icon_url: (untyped icon) -> untyped

    def storage_url_options: -> untyped

    def find_or_initialize_organization_from_param: (untyped param) -> untyped
end
