export const ROUTES = {
    index: "/",
    influence: "/influence",
    signin: "/signin",
    signup: "/signup",
    logout: "/logout",
    passwordreset: "/passwordreset",
    registrationIntroduction: "/registration/introduction",
    registration: "/registration",
    userSettings: "/settings",
    legislators: "/legislators",
    legislator: "/legislator/:localeName/:externalLegislatorId",
    billOfTheWeek: "/bill-of-the-week",
    billOfTheWeekCreator: "/bill-of-the-week-creator",
    bill: (localeName = ":localeName", billFirestoreId = ":billFirestoreId") => `/bill/${localeName}/${billFirestoreId}`,
    pastBills: "/past-bills-of-the-week",
    invite: "/invite/:uid",
}