module Users
    module Webauthn
        class RegistrationController < ApplicationController
            def create: -> untyped

            def callback: -> untyped

            private

            def sanitized_user_attributes: (untyped attributes, untyped verified_phone) -> untyped

            def read_attribute: (untyped attributes, untyped key) -> untyped

            def registration_params: -> untyped
        end
    end
end
