module ::Shortener
    class ::Shortener::ShortenedUrl < ::Shortener::Record
        extend ::ActiveRecord::Base::ClassMethods[::Shortener::ShortenedUrl, ::Shortener::ShortenedUrl::ActiveRecord_Relation, ::Integer]

        module ::Shortener::ShortenedUrl::GeneratedAttributeMethods
            def id: -> ::Integer

            def id=: (::Integer) -> ::Integer

            def id?: -> bool

            def id_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

            def id_change: -> [::Integer?, ::Integer?]

            def id_will_change!: -> void

            def id_was: -> ::Integer?

            def id_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

            def id_previous_change: -> ::Array[::Integer?]?

            def id_previously_was: -> ::Integer?

            def id_before_last_save: -> ::Integer?

            def id_change_to_be_saved: -> ::Array[::Integer?]?

            def id_in_database: -> ::Integer?

            def saved_change_to_id: -> ::Array[::Integer?]?

            def saved_change_to_id?: -> bool

            def will_save_change_to_id?: -> bool

            def restore_id!: -> void

            def clear_id_change: -> void

            def id_before_type_cast: -> ::Integer

            def id_for_database: -> ::Integer

            def category: -> ::String?

            def category=: (::String?) -> ::String?

            def category?: -> bool

            def category_changed?: (?from: ::String?, ?to: ::String?) -> bool

            def category_change: -> [::String?, ::String?]

            def category_will_change!: -> void

            def category_was: -> ::String?

            def category_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

            def category_previous_change: -> ::Array[::String?]?

            def category_previously_was: -> ::String?

            def category_before_last_save: -> ::String?

            def category_change_to_be_saved: -> ::Array[::String?]?

            def category_in_database: -> ::String?

            def saved_change_to_category: -> ::Array[::String?]?

            def saved_change_to_category?: -> bool

            def will_save_change_to_category?: -> bool

            def restore_category!: -> void

            def clear_category_change: -> void

            def category_before_type_cast: -> ::String?

            def category_for_database: -> ::String?

            def created_at: -> ::ActiveSupport::TimeWithZone?

            def created_at=: (::ActiveSupport::TimeWithZone?) -> ::ActiveSupport::TimeWithZone?

            def created_at?: -> bool

            def created_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

            def created_at_change: -> [::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone?]

            def created_at_will_change!: -> void

            def created_at_was: -> ::ActiveSupport::TimeWithZone?

            def created_at_previously_changed?: (
                ?from: ::ActiveSupport::TimeWithZone?,
                ?to: ::ActiveSupport::TimeWithZone?
            ) -> bool

            def created_at_previous_change: -> ::Array[::ActiveSupport::TimeWithZone?]?

            def created_at_previously_was: -> ::ActiveSupport::TimeWithZone?

            def created_at_before_last_save: -> ::ActiveSupport::TimeWithZone?

            def created_at_change_to_be_saved: -> ::Array[::ActiveSupport::TimeWithZone?]?

            def created_at_in_database: -> ::ActiveSupport::TimeWithZone?

            def saved_change_to_created_at: -> ::Array[::ActiveSupport::TimeWithZone?]?

            def saved_change_to_created_at?: -> bool

            def will_save_change_to_created_at?: -> bool

            def restore_created_at!: -> void

            def clear_created_at_change: -> void

            def created_at_before_type_cast: -> ::Time?

            def created_at_for_database: -> ::Time?

            def expires_at: -> ::ActiveSupport::TimeWithZone?

            def expires_at=: (::ActiveSupport::TimeWithZone?) -> ::ActiveSupport::TimeWithZone?

            def expires_at?: -> bool

            def expires_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

            def expires_at_change: -> [::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone?]

            def expires_at_will_change!: -> void

            def expires_at_was: -> ::ActiveSupport::TimeWithZone?

            def expires_at_previously_changed?: (
                ?from: ::ActiveSupport::TimeWithZone?,
                ?to: ::ActiveSupport::TimeWithZone?
            ) -> bool

            def expires_at_previous_change: -> ::Array[::ActiveSupport::TimeWithZone?]?

            def expires_at_previously_was: -> ::ActiveSupport::TimeWithZone?

            def expires_at_before_last_save: -> ::ActiveSupport::TimeWithZone?

            def expires_at_change_to_be_saved: -> ::Array[::ActiveSupport::TimeWithZone?]?

            def expires_at_in_database: -> ::ActiveSupport::TimeWithZone?

            def saved_change_to_expires_at: -> ::Array[::ActiveSupport::TimeWithZone?]?

            def saved_change_to_expires_at?: -> bool

            def will_save_change_to_expires_at?: -> bool

            def restore_expires_at!: -> void

            def clear_expires_at_change: -> void

            def expires_at_before_type_cast: -> ::Time?

            def expires_at_for_database: -> ::Time?

            def owner_id: -> ::Integer?

            def owner_id=: (::Integer?) -> ::Integer?

            def owner_id?: -> bool

            def owner_id_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

            def owner_id_change: -> [::Integer?, ::Integer?]

            def owner_id_will_change!: -> void

            def owner_id_was: -> ::Integer?

            def owner_id_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

            def owner_id_previous_change: -> ::Array[::Integer?]?

            def owner_id_previously_was: -> ::Integer?

            def owner_id_before_last_save: -> ::Integer?

            def owner_id_change_to_be_saved: -> ::Array[::Integer?]?

            def owner_id_in_database: -> ::Integer?

            def saved_change_to_owner_id: -> ::Array[::Integer?]?

            def saved_change_to_owner_id?: -> bool

            def will_save_change_to_owner_id?: -> bool

            def restore_owner_id!: -> void

            def clear_owner_id_change: -> void

            def owner_id_before_type_cast: -> ::Integer?

            def owner_id_for_database: -> ::Integer?

            def owner_type: -> ::String?

            def owner_type=: (::String?) -> ::String?

            def owner_type?: -> bool

            def owner_type_changed?: (?from: ::String?, ?to: ::String?) -> bool

            def owner_type_change: -> [::String?, ::String?]

            def owner_type_will_change!: -> void

            def owner_type_was: -> ::String?

            def owner_type_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

            def owner_type_previous_change: -> ::Array[::String?]?

            def owner_type_previously_was: -> ::String?

            def owner_type_before_last_save: -> ::String?

            def owner_type_change_to_be_saved: -> ::Array[::String?]?

            def owner_type_in_database: -> ::String?

            def saved_change_to_owner_type: -> ::Array[::String?]?

            def saved_change_to_owner_type?: -> bool

            def will_save_change_to_owner_type?: -> bool

            def restore_owner_type!: -> void

            def clear_owner_type_change: -> void

            def owner_type_before_type_cast: -> ::String?

            def owner_type_for_database: -> ::String?

            def unique_key: -> ::String

            def unique_key=: (::String) -> ::String

            def unique_key?: -> bool

            def unique_key_changed?: (?from: ::String?, ?to: ::String?) -> bool

            def unique_key_change: -> [::String?, ::String?]

            def unique_key_will_change!: -> void

            def unique_key_was: -> ::String?

            def unique_key_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

            def unique_key_previous_change: -> ::Array[::String?]?

            def unique_key_previously_was: -> ::String?

            def unique_key_before_last_save: -> ::String?

            def unique_key_change_to_be_saved: -> ::Array[::String?]?

            def unique_key_in_database: -> ::String?

            def saved_change_to_unique_key: -> ::Array[::String?]?

            def saved_change_to_unique_key?: -> bool

            def will_save_change_to_unique_key?: -> bool

            def restore_unique_key!: -> void

            def clear_unique_key_change: -> void

            def unique_key_before_type_cast: -> ::String

            def unique_key_for_database: -> ::String

            def updated_at: -> ::ActiveSupport::TimeWithZone?

            def updated_at=: (::ActiveSupport::TimeWithZone?) -> ::ActiveSupport::TimeWithZone?

            def updated_at?: -> bool

            def updated_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

            def updated_at_change: -> [::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone?]

            def updated_at_will_change!: -> void

            def updated_at_was: -> ::ActiveSupport::TimeWithZone?

            def updated_at_previously_changed?: (
                ?from: ::ActiveSupport::TimeWithZone?,
                ?to: ::ActiveSupport::TimeWithZone?
            ) -> bool

            def updated_at_previous_change: -> ::Array[::ActiveSupport::TimeWithZone?]?

            def updated_at_previously_was: -> ::ActiveSupport::TimeWithZone?

            def updated_at_before_last_save: -> ::ActiveSupport::TimeWithZone?

            def updated_at_change_to_be_saved: -> ::Array[::ActiveSupport::TimeWithZone?]?

            def updated_at_in_database: -> ::ActiveSupport::TimeWithZone?

            def saved_change_to_updated_at: -> ::Array[::ActiveSupport::TimeWithZone?]?

            def saved_change_to_updated_at?: -> bool

            def will_save_change_to_updated_at?: -> bool

            def restore_updated_at!: -> void

            def clear_updated_at_change: -> void

            def updated_at_before_type_cast: -> ::Time?

            def updated_at_for_database: -> ::Time?

            def url: -> ::String

            def url=: (::String) -> ::String

            def url?: -> bool

            def url_changed?: (?from: ::String?, ?to: ::String?) -> bool

            def url_change: -> [::String?, ::String?]

            def url_will_change!: -> void

            def url_was: -> ::String?

            def url_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

            def url_previous_change: -> ::Array[::String?]?

            def url_previously_was: -> ::String?

            def url_before_last_save: -> ::String?

            def url_change_to_be_saved: -> ::Array[::String?]?

            def url_in_database: -> ::String?

            def saved_change_to_url: -> ::Array[::String?]?

            def saved_change_to_url?: -> bool

            def will_save_change_to_url?: -> bool

            def restore_url!: -> void

            def clear_url_change: -> void

            def url_before_type_cast: -> ::String

            def url_for_database: -> ::String

            def use_count: -> ::Integer

            def use_count=: (::Integer) -> ::Integer

            def use_count?: -> bool

            def use_count_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

            def use_count_change: -> [::Integer?, ::Integer?]

            def use_count_will_change!: -> void

            def use_count_was: -> ::Integer?

            def use_count_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

            def use_count_previous_change: -> ::Array[::Integer?]?

            def use_count_previously_was: -> ::Integer?

            def use_count_before_last_save: -> ::Integer?

            def use_count_change_to_be_saved: -> ::Array[::Integer?]?

            def use_count_in_database: -> ::Integer?

            def saved_change_to_use_count: -> ::Array[::Integer?]?

            def saved_change_to_use_count?: -> bool

            def will_save_change_to_use_count?: -> bool

            def restore_use_count!: -> void

            def clear_use_count_change: -> void

            def use_count_before_type_cast: -> ::Integer

            def use_count_for_database: -> ::Integer
        end
        include ::Shortener::ShortenedUrl::GeneratedAttributeMethods
        module ::Shortener::ShortenedUrl::GeneratedAliasAttributeMethods
            include ::Shortener::ShortenedUrl::GeneratedAttributeMethods

            alias id_value id

            alias id_value= id=

            alias id_value? id?

            alias id_value_changed? id_changed?

            alias id_value_change id_change

            alias id_value_will_change! id_will_change!

            alias id_value_was id_was

            alias id_value_previously_changed? id_previously_changed?

            alias id_value_previous_change id_previous_change

            alias id_value_previously_was id_previously_was

            alias id_value_before_last_save id_before_last_save

            alias id_value_change_to_be_saved id_change_to_be_saved

            alias id_value_in_database id_in_database

            alias saved_change_to_id_value saved_change_to_id

            alias saved_change_to_id_value? saved_change_to_id?

            alias will_save_change_to_id_value? will_save_change_to_id?

            alias restore_id_value! restore_id!

            alias clear_id_value_change clear_id_change

            alias id_value_before_type_cast id_before_type_cast

            alias id_value_for_database id_for_database
        end
        include ::Shortener::ShortenedUrl::GeneratedAliasAttributeMethods

        def owner: -> untyped?
        def owner=: (untyped?) -> untyped?
        def reload_owner: -> untyped?
        module ::Shortener::ShortenedUrl::GeneratedAssociationMethods
        end
        include ::Shortener::ShortenedUrl::GeneratedAssociationMethods

        def self.unexpired: -> ::Shortener::ShortenedUrl::ActiveRecord_Relation

        module ::Shortener::ShortenedUrl::GeneratedRelationMethods
            def unexpired: -> ::Shortener::ShortenedUrl::ActiveRecord_Relation
        end

        class ::Shortener::ShortenedUrl::ActiveRecord_Relation < ::ActiveRecord::Relation
            include ::Enumerable[::Shortener::ShortenedUrl]
            include ::Shortener::ShortenedUrl::GeneratedRelationMethods
            include ::ActiveRecord::Relation::Methods[::Shortener::ShortenedUrl, ::Integer]
        end

        class ::Shortener::ShortenedUrl::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
            include ::Enumerable[::Shortener::ShortenedUrl]
            include ::Shortener::ShortenedUrl::GeneratedRelationMethods
            include ::ActiveRecord::Relation::Methods[::Shortener::ShortenedUrl, ::Integer]

            def build:
                (
                    ?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes
                ) ?{
                    -> untyped
                } -> ::Shortener::ShortenedUrl
                | (
                    ::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes
                ) ?{
                    -> untyped
                } -> ::Array[::Shortener::ShortenedUrl]
            def create:
                (
                    ?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes
                ) ?{
                    -> untyped
                } -> ::Shortener::ShortenedUrl
                | (
                    ::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes
                ) ?{
                    -> untyped
                } -> ::Array[::Shortener::ShortenedUrl]
            def create!:
                (
                    ?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes
                ) ?{
                    -> untyped
                } -> ::Shortener::ShortenedUrl
                | (
                    ::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes
                ) ?{
                    -> untyped
                } -> ::Array[::Shortener::ShortenedUrl]
            def reload: -> ::Array[::Shortener::ShortenedUrl]

            def replace: (::Array[::Shortener::ShortenedUrl]) -> void
            def delete: (*::Shortener::ShortenedUrl | ::Integer) -> ::Array[::Shortener::ShortenedUrl]
            def destroy: (*::Shortener::ShortenedUrl | ::Integer) -> ::Array[::Shortener::ShortenedUrl]
            def <<: (*::Shortener::ShortenedUrl | ::Array[::Shortener::ShortenedUrl]) -> self
            def `prepend`: (*::Shortener::ShortenedUrl | ::Array[::Shortener::ShortenedUrl]) -> self
        end
    end
end

module ::Shortener
end

class ::Shortener::Record < ::ActiveRecord::Base
end
