module Census
    # https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/tigerWMS_ACS2024/MapServer/54/query?geometry=-76.61571188295052,39.30741100497873&geometryType=esriGeometryPoint&inSR=4269&spatialRel=esriSpatialRelIntersects&returnGeometry=true&f=json&outFields=STATE,CD119
    CONGRESS: 119

    CENSUS_QUERY_URL: ::String

    class Congress
        @address: untyped

        @request: untyped

        @_data: untyped

        def initialize: (untyped address) -> void

        def congressional_district: -> untyped

        # {
        #     displayFieldName: string;
        #     fieldAliases: { STATE: "STATE"; 119: "119" };
        #     geometryType: "esriGeometryPolygon";
        #     spatialReference: { wkid: number; latestWkid: number };
        #     fields: [
        #         {
        #             name: "STATE";
        #             type: "esriFieldTypeString";
        #             alias: "STATE";
        #             length: 2;
        #         },
        #         {
        #             name: "119";
        #             type: "esriFieldTypeString";
        #             alias: "119";
        #             length: 2;
        #         },
        #     ];
        #     features: [
        #         {
        #             attributes: { STATE: string; 119?: string; CD117?: string; CD116?: string };
        #             geometry: {
        #                 rings: [number, number][][];
        #             };
        #         },
        #     ];
        # }
        def request: -> untyped

        def data: -> untyped

        private

        def query_url: -> untyped
    end
end
