version: "3.9"
services:
    sway:
        container_name: sway
        image: sway:latest
        restart: unless-stopped
        env_file: ${PWD}/.env.production
        ports:
            - "127.0.0.1:3333:3333"
        links:
            - sway-postgres
        depends_on:
            - sway-postgres
        networks:
            - sway

    sway-postgres:
        container_name: sway-postgres
        image: postgres:16.2
        restart: unless-stopped
        env_file: ${PWD}/docker/environment/db.env
        volumes:
            - sway_postgres_data:/var/lib/postgresql/data
        networks:
            - sway

volumes:
    sway_postgres_data:
        driver: local

networks:
    sway:
        driver: bridge
