class OnDeactivatedPhoneDeleteUserJob < ApplicationJob
    @deactivated_phones: Array[String]

    def perform: (*untyped _args) -> void

    def deactivated_phones: -> Array[String]

    def deactivation_url: -> untyped

    def twilio_client: -> Twilio::REST::Client
end
